/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WmsRouteImport } from './routes/_wms'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WmsWaveCreationRouteImport } from './routes/_wms.wave-creation'
import { Route as WmsViewManifestRouteImport } from './routes/_wms.view-manifest'
import { Route as WmsViewDispatchRouteImport } from './routes/_wms.view-dispatch'
import { Route as WmsVendorScorecardsRouteImport } from './routes/_wms.vendor-scorecards'
import { Route as WmsUsersRolesRouteImport } from './routes/_wms.users-roles'
import { Route as WmsUnloadingRouteImport } from './routes/_wms.unloading'
import { Route as WmsTrendsRouteImport } from './routes/_wms.trends'
import { Route as WmsStuckOrdersRouteImport } from './routes/_wms.stuck-orders'
import { Route as WmsSlottingConfigRouteImport } from './routes/_wms.slotting-config'
import { Route as WmsSlottingRouteImport } from './routes/_wms.slotting'
import { Route as WmsSitePerformanceRouteImport } from './routes/_wms.site-performance'
import { Route as WmsSalesReturnGrnRouteImport } from './routes/_wms.sales-return-grn'
import { Route as WmsReturnsRtvRouteImport } from './routes/_wms.returns-rtv'
import { Route as WmsReturnsRtoRouteImport } from './routes/_wms.returns-rto'
import { Route as WmsReturnsIntakeRouteImport } from './routes/_wms.returns-intake'
import { Route as WmsReturnsEvaluationRouteImport } from './routes/_wms.returns-evaluation'
import { Route as WmsReturnsCirRouteImport } from './routes/_wms.returns-cir'
import { Route as WmsReportsRouteImport } from './routes/_wms.reports'
import { Route as WmsReplenishmentSetupRouteImport } from './routes/_wms.replenishment-setup'
import { Route as WmsReplenishmentRouteImport } from './routes/_wms.replenishment'
import { Route as WmsRecoveryQueueRouteImport } from './routes/_wms.recovery-queue'
import { Route as WmsQcStationRouteImport } from './routes/_wms.qc-station'
import { Route as WmsPutwallRouteImport } from './routes/_wms.putwall'
import { Route as WmsPutawayRouteImport } from './routes/_wms.putaway'
import { Route as WmsPoliciesRouteImport } from './routes/_wms.policies'
import { Route as WmsPackRouteImport } from './routes/_wms.pack'
import { Route as WmsOutboundExceptionsRouteImport } from './routes/_wms.outbound-exceptions'
import { Route as WmsMovementTaskCreateRouteImport } from './routes/_wms.movement-task-create'
import { Route as WmsMasterDataRouteImport } from './routes/_wms.master-data'
import { Route as WmsManifestRouteImport } from './routes/_wms.manifest'
import { Route as WmsKittingRouteImport } from './routes/_wms.kitting'
import { Route as WmsKitOrderRouteImport } from './routes/_wms.kit-order'
import { Route as WmsKitMappingRouteImport } from './routes/_wms.kit-mapping'
import { Route as WmsItemMovementRouteImport } from './routes/_wms.item-movement'
import { Route as WmsItemInfoUpdateRouteImport } from './routes/_wms.item-info-update'
import { Route as WmsIncidentsRouteImport } from './routes/_wms.incidents'
import { Route as WmsInboundExceptionsRouteImport } from './routes/_wms.inbound-exceptions'
import { Route as WmsGrnRouteImport } from './routes/_wms.grn'
import { Route as WmsGatepassLogRouteImport } from './routes/_wms.gatepass-log'
import { Route as WmsGateEntryRouteImport } from './routes/_wms.gate-entry'
import { Route as WmsFloorHandheldsRouteImport } from './routes/_wms.floor-handhelds'
import { Route as WmsDriftFeedbackRouteImport } from './routes/_wms.drift-feedback'
import { Route as WmsDockManagementRouteImport } from './routes/_wms.dock-management'
import { Route as WmsDispatchRouteImport } from './routes/_wms.dispatch'
import { Route as WmsDetailedInventoryViewRouteImport } from './routes/_wms.detailed-inventory-view'
import { Route as WmsDashboardRouteImport } from './routes/_wms.dashboard'
import { Route as WmsCycleCountRouteImport } from './routes/_wms.cycle-count'
import { Route as WmsCustomerDisputesRouteImport } from './routes/_wms.customer-disputes'
import { Route as WmsControlTowerRouteImport } from './routes/_wms.control-tower'
import { Route as WmsCarrierScorecardsRouteImport } from './routes/_wms.carrier-scorecards'
import { Route as WmsBillingLeakageRouteImport } from './routes/_wms.billing-leakage'
import { Route as WmsAuditLogRouteImport } from './routes/_wms.audit-log'
import { Route as WmsApprovalsRouteImport } from './routes/_wms.approvals'
import { Route as WmsAlertsRouteImport } from './routes/_wms.alerts'
import { Route as WmsAgentHealthRouteImport } from './routes/_wms.agent-health'
import { Route as WmsAgentDirectoryRouteImport } from './routes/_wms.agent-directory'
import { Route as WmsAdminRouteImport } from './routes/_wms.admin'
import { Route as WmsViewPicklistIndexRouteImport } from './routes/_wms.view-picklist.index'
import { Route as WmsViewPackIndexRouteImport } from './routes/_wms.view-pack.index'
import { Route as WmsSortIndexRouteImport } from './routes/_wms.sort.index'
import { Route as WmsPickIndexRouteImport } from './routes/_wms.pick.index'
import { Route as WmsOrdersIndexRouteImport } from './routes/_wms.orders.index'
import { Route as WmsViewPicklistPicklistIdRouteImport } from './routes/_wms.view-picklist.$picklistId'
import { Route as WmsViewPackPacklistIdRouteImport } from './routes/_wms.view-pack.$packlistId'
import { Route as WmsSortTaskIdRouteImport } from './routes/_wms.sort.$taskId'
import { Route as WmsPickPicklistIdRouteImport } from './routes/_wms.pick.$picklistId'
import { Route as WmsOrdersOrderNoRouteImport } from './routes/_wms.orders.$orderNo'

const WmsRoute = WmsRouteImport.update({
  id: '/_wms',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WmsWaveCreationRoute = WmsWaveCreationRouteImport.update({
  id: '/wave-creation',
  path: '/wave-creation',
  getParentRoute: () => WmsRoute,
} as any)
const WmsViewManifestRoute = WmsViewManifestRouteImport.update({
  id: '/view-manifest',
  path: '/view-manifest',
  getParentRoute: () => WmsRoute,
} as any)
const WmsViewDispatchRoute = WmsViewDispatchRouteImport.update({
  id: '/view-dispatch',
  path: '/view-dispatch',
  getParentRoute: () => WmsRoute,
} as any)
const WmsVendorScorecardsRoute = WmsVendorScorecardsRouteImport.update({
  id: '/vendor-scorecards',
  path: '/vendor-scorecards',
  getParentRoute: () => WmsRoute,
} as any)
const WmsUsersRolesRoute = WmsUsersRolesRouteImport.update({
  id: '/users-roles',
  path: '/users-roles',
  getParentRoute: () => WmsRoute,
} as any)
const WmsUnloadingRoute = WmsUnloadingRouteImport.update({
  id: '/unloading',
  path: '/unloading',
  getParentRoute: () => WmsRoute,
} as any)
const WmsTrendsRoute = WmsTrendsRouteImport.update({
  id: '/trends',
  path: '/trends',
  getParentRoute: () => WmsRoute,
} as any)
const WmsStuckOrdersRoute = WmsStuckOrdersRouteImport.update({
  id: '/stuck-orders',
  path: '/stuck-orders',
  getParentRoute: () => WmsRoute,
} as any)
const WmsSlottingConfigRoute = WmsSlottingConfigRouteImport.update({
  id: '/slotting-config',
  path: '/slotting-config',
  getParentRoute: () => WmsRoute,
} as any)
const WmsSlottingRoute = WmsSlottingRouteImport.update({
  id: '/slotting',
  path: '/slotting',
  getParentRoute: () => WmsRoute,
} as any)
const WmsSitePerformanceRoute = WmsSitePerformanceRouteImport.update({
  id: '/site-performance',
  path: '/site-performance',
  getParentRoute: () => WmsRoute,
} as any)
const WmsSalesReturnGrnRoute = WmsSalesReturnGrnRouteImport.update({
  id: '/sales-return-grn',
  path: '/sales-return-grn',
  getParentRoute: () => WmsRoute,
} as any)
const WmsReturnsRtvRoute = WmsReturnsRtvRouteImport.update({
  id: '/returns-rtv',
  path: '/returns-rtv',
  getParentRoute: () => WmsRoute,
} as any)
const WmsReturnsRtoRoute = WmsReturnsRtoRouteImport.update({
  id: '/returns-rto',
  path: '/returns-rto',
  getParentRoute: () => WmsRoute,
} as any)
const WmsReturnsIntakeRoute = WmsReturnsIntakeRouteImport.update({
  id: '/returns-intake',
  path: '/returns-intake',
  getParentRoute: () => WmsRoute,
} as any)
const WmsReturnsEvaluationRoute = WmsReturnsEvaluationRouteImport.update({
  id: '/returns-evaluation',
  path: '/returns-evaluation',
  getParentRoute: () => WmsRoute,
} as any)
const WmsReturnsCirRoute = WmsReturnsCirRouteImport.update({
  id: '/returns-cir',
  path: '/returns-cir',
  getParentRoute: () => WmsRoute,
} as any)
const WmsReportsRoute = WmsReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => WmsRoute,
} as any)
const WmsReplenishmentSetupRoute = WmsReplenishmentSetupRouteImport.update({
  id: '/replenishment-setup',
  path: '/replenishment-setup',
  getParentRoute: () => WmsRoute,
} as any)
const WmsReplenishmentRoute = WmsReplenishmentRouteImport.update({
  id: '/replenishment',
  path: '/replenishment',
  getParentRoute: () => WmsRoute,
} as any)
const WmsRecoveryQueueRoute = WmsRecoveryQueueRouteImport.update({
  id: '/recovery-queue',
  path: '/recovery-queue',
  getParentRoute: () => WmsRoute,
} as any)
const WmsQcStationRoute = WmsQcStationRouteImport.update({
  id: '/qc-station',
  path: '/qc-station',
  getParentRoute: () => WmsRoute,
} as any)
const WmsPutwallRoute = WmsPutwallRouteImport.update({
  id: '/putwall',
  path: '/putwall',
  getParentRoute: () => WmsRoute,
} as any)
const WmsPutawayRoute = WmsPutawayRouteImport.update({
  id: '/putaway',
  path: '/putaway',
  getParentRoute: () => WmsRoute,
} as any)
const WmsPoliciesRoute = WmsPoliciesRouteImport.update({
  id: '/policies',
  path: '/policies',
  getParentRoute: () => WmsRoute,
} as any)
const WmsPackRoute = WmsPackRouteImport.update({
  id: '/pack',
  path: '/pack',
  getParentRoute: () => WmsRoute,
} as any)
const WmsOutboundExceptionsRoute = WmsOutboundExceptionsRouteImport.update({
  id: '/outbound-exceptions',
  path: '/outbound-exceptions',
  getParentRoute: () => WmsRoute,
} as any)
const WmsMovementTaskCreateRoute = WmsMovementTaskCreateRouteImport.update({
  id: '/movement-task-create',
  path: '/movement-task-create',
  getParentRoute: () => WmsRoute,
} as any)
const WmsMasterDataRoute = WmsMasterDataRouteImport.update({
  id: '/master-data',
  path: '/master-data',
  getParentRoute: () => WmsRoute,
} as any)
const WmsManifestRoute = WmsManifestRouteImport.update({
  id: '/manifest',
  path: '/manifest',
  getParentRoute: () => WmsRoute,
} as any)
const WmsKittingRoute = WmsKittingRouteImport.update({
  id: '/kitting',
  path: '/kitting',
  getParentRoute: () => WmsRoute,
} as any)
const WmsKitOrderRoute = WmsKitOrderRouteImport.update({
  id: '/kit-order',
  path: '/kit-order',
  getParentRoute: () => WmsRoute,
} as any)
const WmsKitMappingRoute = WmsKitMappingRouteImport.update({
  id: '/kit-mapping',
  path: '/kit-mapping',
  getParentRoute: () => WmsRoute,
} as any)
const WmsItemMovementRoute = WmsItemMovementRouteImport.update({
  id: '/item-movement',
  path: '/item-movement',
  getParentRoute: () => WmsRoute,
} as any)
const WmsItemInfoUpdateRoute = WmsItemInfoUpdateRouteImport.update({
  id: '/item-info-update',
  path: '/item-info-update',
  getParentRoute: () => WmsRoute,
} as any)
const WmsIncidentsRoute = WmsIncidentsRouteImport.update({
  id: '/incidents',
  path: '/incidents',
  getParentRoute: () => WmsRoute,
} as any)
const WmsInboundExceptionsRoute = WmsInboundExceptionsRouteImport.update({
  id: '/inbound-exceptions',
  path: '/inbound-exceptions',
  getParentRoute: () => WmsRoute,
} as any)
const WmsGrnRoute = WmsGrnRouteImport.update({
  id: '/grn',
  path: '/grn',
  getParentRoute: () => WmsRoute,
} as any)
const WmsGatepassLogRoute = WmsGatepassLogRouteImport.update({
  id: '/gatepass-log',
  path: '/gatepass-log',
  getParentRoute: () => WmsRoute,
} as any)
const WmsGateEntryRoute = WmsGateEntryRouteImport.update({
  id: '/gate-entry',
  path: '/gate-entry',
  getParentRoute: () => WmsRoute,
} as any)
const WmsFloorHandheldsRoute = WmsFloorHandheldsRouteImport.update({
  id: '/floor-handhelds',
  path: '/floor-handhelds',
  getParentRoute: () => WmsRoute,
} as any)
const WmsDriftFeedbackRoute = WmsDriftFeedbackRouteImport.update({
  id: '/drift-feedback',
  path: '/drift-feedback',
  getParentRoute: () => WmsRoute,
} as any)
const WmsDockManagementRoute = WmsDockManagementRouteImport.update({
  id: '/dock-management',
  path: '/dock-management',
  getParentRoute: () => WmsRoute,
} as any)
const WmsDispatchRoute = WmsDispatchRouteImport.update({
  id: '/dispatch',
  path: '/dispatch',
  getParentRoute: () => WmsRoute,
} as any)
const WmsDetailedInventoryViewRoute =
  WmsDetailedInventoryViewRouteImport.update({
    id: '/detailed-inventory-view',
    path: '/detailed-inventory-view',
    getParentRoute: () => WmsRoute,
  } as any)
const WmsDashboardRoute = WmsDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => WmsRoute,
} as any)
const WmsCycleCountRoute = WmsCycleCountRouteImport.update({
  id: '/cycle-count',
  path: '/cycle-count',
  getParentRoute: () => WmsRoute,
} as any)
const WmsCustomerDisputesRoute = WmsCustomerDisputesRouteImport.update({
  id: '/customer-disputes',
  path: '/customer-disputes',
  getParentRoute: () => WmsRoute,
} as any)
const WmsControlTowerRoute = WmsControlTowerRouteImport.update({
  id: '/control-tower',
  path: '/control-tower',
  getParentRoute: () => WmsRoute,
} as any)
const WmsCarrierScorecardsRoute = WmsCarrierScorecardsRouteImport.update({
  id: '/carrier-scorecards',
  path: '/carrier-scorecards',
  getParentRoute: () => WmsRoute,
} as any)
const WmsBillingLeakageRoute = WmsBillingLeakageRouteImport.update({
  id: '/billing-leakage',
  path: '/billing-leakage',
  getParentRoute: () => WmsRoute,
} as any)
const WmsAuditLogRoute = WmsAuditLogRouteImport.update({
  id: '/audit-log',
  path: '/audit-log',
  getParentRoute: () => WmsRoute,
} as any)
const WmsApprovalsRoute = WmsApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => WmsRoute,
} as any)
const WmsAlertsRoute = WmsAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => WmsRoute,
} as any)
const WmsAgentHealthRoute = WmsAgentHealthRouteImport.update({
  id: '/agent-health',
  path: '/agent-health',
  getParentRoute: () => WmsRoute,
} as any)
const WmsAgentDirectoryRoute = WmsAgentDirectoryRouteImport.update({
  id: '/agent-directory',
  path: '/agent-directory',
  getParentRoute: () => WmsRoute,
} as any)
const WmsAdminRoute = WmsAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => WmsRoute,
} as any)
const WmsViewPicklistIndexRoute = WmsViewPicklistIndexRouteImport.update({
  id: '/view-picklist/',
  path: '/view-picklist/',
  getParentRoute: () => WmsRoute,
} as any)
const WmsViewPackIndexRoute = WmsViewPackIndexRouteImport.update({
  id: '/view-pack/',
  path: '/view-pack/',
  getParentRoute: () => WmsRoute,
} as any)
const WmsSortIndexRoute = WmsSortIndexRouteImport.update({
  id: '/sort/',
  path: '/sort/',
  getParentRoute: () => WmsRoute,
} as any)
const WmsPickIndexRoute = WmsPickIndexRouteImport.update({
  id: '/pick/',
  path: '/pick/',
  getParentRoute: () => WmsRoute,
} as any)
const WmsOrdersIndexRoute = WmsOrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => WmsRoute,
} as any)
const WmsViewPicklistPicklistIdRoute =
  WmsViewPicklistPicklistIdRouteImport.update({
    id: '/view-picklist/$picklistId',
    path: '/view-picklist/$picklistId',
    getParentRoute: () => WmsRoute,
  } as any)
const WmsViewPackPacklistIdRoute = WmsViewPackPacklistIdRouteImport.update({
  id: '/view-pack/$packlistId',
  path: '/view-pack/$packlistId',
  getParentRoute: () => WmsRoute,
} as any)
const WmsSortTaskIdRoute = WmsSortTaskIdRouteImport.update({
  id: '/sort/$taskId',
  path: '/sort/$taskId',
  getParentRoute: () => WmsRoute,
} as any)
const WmsPickPicklistIdRoute = WmsPickPicklistIdRouteImport.update({
  id: '/pick/$picklistId',
  path: '/pick/$picklistId',
  getParentRoute: () => WmsRoute,
} as any)
const WmsOrdersOrderNoRoute = WmsOrdersOrderNoRouteImport.update({
  id: '/orders/$orderNo',
  path: '/orders/$orderNo',
  getParentRoute: () => WmsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof WmsAdminRoute
  '/agent-directory': typeof WmsAgentDirectoryRoute
  '/agent-health': typeof WmsAgentHealthRoute
  '/alerts': typeof WmsAlertsRoute
  '/approvals': typeof WmsApprovalsRoute
  '/audit-log': typeof WmsAuditLogRoute
  '/billing-leakage': typeof WmsBillingLeakageRoute
  '/carrier-scorecards': typeof WmsCarrierScorecardsRoute
  '/control-tower': typeof WmsControlTowerRoute
  '/customer-disputes': typeof WmsCustomerDisputesRoute
  '/cycle-count': typeof WmsCycleCountRoute
  '/dashboard': typeof WmsDashboardRoute
  '/detailed-inventory-view': typeof WmsDetailedInventoryViewRoute
  '/dispatch': typeof WmsDispatchRoute
  '/dock-management': typeof WmsDockManagementRoute
  '/drift-feedback': typeof WmsDriftFeedbackRoute
  '/floor-handhelds': typeof WmsFloorHandheldsRoute
  '/gate-entry': typeof WmsGateEntryRoute
  '/gatepass-log': typeof WmsGatepassLogRoute
  '/grn': typeof WmsGrnRoute
  '/inbound-exceptions': typeof WmsInboundExceptionsRoute
  '/incidents': typeof WmsIncidentsRoute
  '/item-info-update': typeof WmsItemInfoUpdateRoute
  '/item-movement': typeof WmsItemMovementRoute
  '/kit-mapping': typeof WmsKitMappingRoute
  '/kit-order': typeof WmsKitOrderRoute
  '/kitting': typeof WmsKittingRoute
  '/manifest': typeof WmsManifestRoute
  '/master-data': typeof WmsMasterDataRoute
  '/movement-task-create': typeof WmsMovementTaskCreateRoute
  '/outbound-exceptions': typeof WmsOutboundExceptionsRoute
  '/pack': typeof WmsPackRoute
  '/policies': typeof WmsPoliciesRoute
  '/putaway': typeof WmsPutawayRoute
  '/putwall': typeof WmsPutwallRoute
  '/qc-station': typeof WmsQcStationRoute
  '/recovery-queue': typeof WmsRecoveryQueueRoute
  '/replenishment': typeof WmsReplenishmentRoute
  '/replenishment-setup': typeof WmsReplenishmentSetupRoute
  '/reports': typeof WmsReportsRoute
  '/returns-cir': typeof WmsReturnsCirRoute
  '/returns-evaluation': typeof WmsReturnsEvaluationRoute
  '/returns-intake': typeof WmsReturnsIntakeRoute
  '/returns-rto': typeof WmsReturnsRtoRoute
  '/returns-rtv': typeof WmsReturnsRtvRoute
  '/sales-return-grn': typeof WmsSalesReturnGrnRoute
  '/site-performance': typeof WmsSitePerformanceRoute
  '/slotting': typeof WmsSlottingRoute
  '/slotting-config': typeof WmsSlottingConfigRoute
  '/stuck-orders': typeof WmsStuckOrdersRoute
  '/trends': typeof WmsTrendsRoute
  '/unloading': typeof WmsUnloadingRoute
  '/users-roles': typeof WmsUsersRolesRoute
  '/vendor-scorecards': typeof WmsVendorScorecardsRoute
  '/view-dispatch': typeof WmsViewDispatchRoute
  '/view-manifest': typeof WmsViewManifestRoute
  '/wave-creation': typeof WmsWaveCreationRoute
  '/orders/$orderNo': typeof WmsOrdersOrderNoRoute
  '/pick/$picklistId': typeof WmsPickPicklistIdRoute
  '/sort/$taskId': typeof WmsSortTaskIdRoute
  '/view-pack/$packlistId': typeof WmsViewPackPacklistIdRoute
  '/view-picklist/$picklistId': typeof WmsViewPicklistPicklistIdRoute
  '/orders/': typeof WmsOrdersIndexRoute
  '/pick/': typeof WmsPickIndexRoute
  '/sort/': typeof WmsSortIndexRoute
  '/view-pack/': typeof WmsViewPackIndexRoute
  '/view-picklist/': typeof WmsViewPicklistIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof WmsAdminRoute
  '/agent-directory': typeof WmsAgentDirectoryRoute
  '/agent-health': typeof WmsAgentHealthRoute
  '/alerts': typeof WmsAlertsRoute
  '/approvals': typeof WmsApprovalsRoute
  '/audit-log': typeof WmsAuditLogRoute
  '/billing-leakage': typeof WmsBillingLeakageRoute
  '/carrier-scorecards': typeof WmsCarrierScorecardsRoute
  '/control-tower': typeof WmsControlTowerRoute
  '/customer-disputes': typeof WmsCustomerDisputesRoute
  '/cycle-count': typeof WmsCycleCountRoute
  '/dashboard': typeof WmsDashboardRoute
  '/detailed-inventory-view': typeof WmsDetailedInventoryViewRoute
  '/dispatch': typeof WmsDispatchRoute
  '/dock-management': typeof WmsDockManagementRoute
  '/drift-feedback': typeof WmsDriftFeedbackRoute
  '/floor-handhelds': typeof WmsFloorHandheldsRoute
  '/gate-entry': typeof WmsGateEntryRoute
  '/gatepass-log': typeof WmsGatepassLogRoute
  '/grn': typeof WmsGrnRoute
  '/inbound-exceptions': typeof WmsInboundExceptionsRoute
  '/incidents': typeof WmsIncidentsRoute
  '/item-info-update': typeof WmsItemInfoUpdateRoute
  '/item-movement': typeof WmsItemMovementRoute
  '/kit-mapping': typeof WmsKitMappingRoute
  '/kit-order': typeof WmsKitOrderRoute
  '/kitting': typeof WmsKittingRoute
  '/manifest': typeof WmsManifestRoute
  '/master-data': typeof WmsMasterDataRoute
  '/movement-task-create': typeof WmsMovementTaskCreateRoute
  '/outbound-exceptions': typeof WmsOutboundExceptionsRoute
  '/pack': typeof WmsPackRoute
  '/policies': typeof WmsPoliciesRoute
  '/putaway': typeof WmsPutawayRoute
  '/putwall': typeof WmsPutwallRoute
  '/qc-station': typeof WmsQcStationRoute
  '/recovery-queue': typeof WmsRecoveryQueueRoute
  '/replenishment': typeof WmsReplenishmentRoute
  '/replenishment-setup': typeof WmsReplenishmentSetupRoute
  '/reports': typeof WmsReportsRoute
  '/returns-cir': typeof WmsReturnsCirRoute
  '/returns-evaluation': typeof WmsReturnsEvaluationRoute
  '/returns-intake': typeof WmsReturnsIntakeRoute
  '/returns-rto': typeof WmsReturnsRtoRoute
  '/returns-rtv': typeof WmsReturnsRtvRoute
  '/sales-return-grn': typeof WmsSalesReturnGrnRoute
  '/site-performance': typeof WmsSitePerformanceRoute
  '/slotting': typeof WmsSlottingRoute
  '/slotting-config': typeof WmsSlottingConfigRoute
  '/stuck-orders': typeof WmsStuckOrdersRoute
  '/trends': typeof WmsTrendsRoute
  '/unloading': typeof WmsUnloadingRoute
  '/users-roles': typeof WmsUsersRolesRoute
  '/vendor-scorecards': typeof WmsVendorScorecardsRoute
  '/view-dispatch': typeof WmsViewDispatchRoute
  '/view-manifest': typeof WmsViewManifestRoute
  '/wave-creation': typeof WmsWaveCreationRoute
  '/orders/$orderNo': typeof WmsOrdersOrderNoRoute
  '/pick/$picklistId': typeof WmsPickPicklistIdRoute
  '/sort/$taskId': typeof WmsSortTaskIdRoute
  '/view-pack/$packlistId': typeof WmsViewPackPacklistIdRoute
  '/view-picklist/$picklistId': typeof WmsViewPicklistPicklistIdRoute
  '/orders': typeof WmsOrdersIndexRoute
  '/pick': typeof WmsPickIndexRoute
  '/sort': typeof WmsSortIndexRoute
  '/view-pack': typeof WmsViewPackIndexRoute
  '/view-picklist': typeof WmsViewPicklistIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_wms': typeof WmsRouteWithChildren
  '/_wms/admin': typeof WmsAdminRoute
  '/_wms/agent-directory': typeof WmsAgentDirectoryRoute
  '/_wms/agent-health': typeof WmsAgentHealthRoute
  '/_wms/alerts': typeof WmsAlertsRoute
  '/_wms/approvals': typeof WmsApprovalsRoute
  '/_wms/audit-log': typeof WmsAuditLogRoute
  '/_wms/billing-leakage': typeof WmsBillingLeakageRoute
  '/_wms/carrier-scorecards': typeof WmsCarrierScorecardsRoute
  '/_wms/control-tower': typeof WmsControlTowerRoute
  '/_wms/customer-disputes': typeof WmsCustomerDisputesRoute
  '/_wms/cycle-count': typeof WmsCycleCountRoute
  '/_wms/dashboard': typeof WmsDashboardRoute
  '/_wms/detailed-inventory-view': typeof WmsDetailedInventoryViewRoute
  '/_wms/dispatch': typeof WmsDispatchRoute
  '/_wms/dock-management': typeof WmsDockManagementRoute
  '/_wms/drift-feedback': typeof WmsDriftFeedbackRoute
  '/_wms/floor-handhelds': typeof WmsFloorHandheldsRoute
  '/_wms/gate-entry': typeof WmsGateEntryRoute
  '/_wms/gatepass-log': typeof WmsGatepassLogRoute
  '/_wms/grn': typeof WmsGrnRoute
  '/_wms/inbound-exceptions': typeof WmsInboundExceptionsRoute
  '/_wms/incidents': typeof WmsIncidentsRoute
  '/_wms/item-info-update': typeof WmsItemInfoUpdateRoute
  '/_wms/item-movement': typeof WmsItemMovementRoute
  '/_wms/kit-mapping': typeof WmsKitMappingRoute
  '/_wms/kit-order': typeof WmsKitOrderRoute
  '/_wms/kitting': typeof WmsKittingRoute
  '/_wms/manifest': typeof WmsManifestRoute
  '/_wms/master-data': typeof WmsMasterDataRoute
  '/_wms/movement-task-create': typeof WmsMovementTaskCreateRoute
  '/_wms/outbound-exceptions': typeof WmsOutboundExceptionsRoute
  '/_wms/pack': typeof WmsPackRoute
  '/_wms/policies': typeof WmsPoliciesRoute
  '/_wms/putaway': typeof WmsPutawayRoute
  '/_wms/putwall': typeof WmsPutwallRoute
  '/_wms/qc-station': typeof WmsQcStationRoute
  '/_wms/recovery-queue': typeof WmsRecoveryQueueRoute
  '/_wms/replenishment': typeof WmsReplenishmentRoute
  '/_wms/replenishment-setup': typeof WmsReplenishmentSetupRoute
  '/_wms/reports': typeof WmsReportsRoute
  '/_wms/returns-cir': typeof WmsReturnsCirRoute
  '/_wms/returns-evaluation': typeof WmsReturnsEvaluationRoute
  '/_wms/returns-intake': typeof WmsReturnsIntakeRoute
  '/_wms/returns-rto': typeof WmsReturnsRtoRoute
  '/_wms/returns-rtv': typeof WmsReturnsRtvRoute
  '/_wms/sales-return-grn': typeof WmsSalesReturnGrnRoute
  '/_wms/site-performance': typeof WmsSitePerformanceRoute
  '/_wms/slotting': typeof WmsSlottingRoute
  '/_wms/slotting-config': typeof WmsSlottingConfigRoute
  '/_wms/stuck-orders': typeof WmsStuckOrdersRoute
  '/_wms/trends': typeof WmsTrendsRoute
  '/_wms/unloading': typeof WmsUnloadingRoute
  '/_wms/users-roles': typeof WmsUsersRolesRoute
  '/_wms/vendor-scorecards': typeof WmsVendorScorecardsRoute
  '/_wms/view-dispatch': typeof WmsViewDispatchRoute
  '/_wms/view-manifest': typeof WmsViewManifestRoute
  '/_wms/wave-creation': typeof WmsWaveCreationRoute
  '/_wms/orders/$orderNo': typeof WmsOrdersOrderNoRoute
  '/_wms/pick/$picklistId': typeof WmsPickPicklistIdRoute
  '/_wms/sort/$taskId': typeof WmsSortTaskIdRoute
  '/_wms/view-pack/$packlistId': typeof WmsViewPackPacklistIdRoute
  '/_wms/view-picklist/$picklistId': typeof WmsViewPicklistPicklistIdRoute
  '/_wms/orders/': typeof WmsOrdersIndexRoute
  '/_wms/pick/': typeof WmsPickIndexRoute
  '/_wms/sort/': typeof WmsSortIndexRoute
  '/_wms/view-pack/': typeof WmsViewPackIndexRoute
  '/_wms/view-picklist/': typeof WmsViewPicklistIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/agent-directory'
    | '/agent-health'
    | '/alerts'
    | '/approvals'
    | '/audit-log'
    | '/billing-leakage'
    | '/carrier-scorecards'
    | '/control-tower'
    | '/customer-disputes'
    | '/cycle-count'
    | '/dashboard'
    | '/detailed-inventory-view'
    | '/dispatch'
    | '/dock-management'
    | '/drift-feedback'
    | '/floor-handhelds'
    | '/gate-entry'
    | '/gatepass-log'
    | '/grn'
    | '/inbound-exceptions'
    | '/incidents'
    | '/item-info-update'
    | '/item-movement'
    | '/kit-mapping'
    | '/kit-order'
    | '/kitting'
    | '/manifest'
    | '/master-data'
    | '/movement-task-create'
    | '/outbound-exceptions'
    | '/pack'
    | '/policies'
    | '/putaway'
    | '/putwall'
    | '/qc-station'
    | '/recovery-queue'
    | '/replenishment'
    | '/replenishment-setup'
    | '/reports'
    | '/returns-cir'
    | '/returns-evaluation'
    | '/returns-intake'
    | '/returns-rto'
    | '/returns-rtv'
    | '/sales-return-grn'
    | '/site-performance'
    | '/slotting'
    | '/slotting-config'
    | '/stuck-orders'
    | '/trends'
    | '/unloading'
    | '/users-roles'
    | '/vendor-scorecards'
    | '/view-dispatch'
    | '/view-manifest'
    | '/wave-creation'
    | '/orders/$orderNo'
    | '/pick/$picklistId'
    | '/sort/$taskId'
    | '/view-pack/$packlistId'
    | '/view-picklist/$picklistId'
    | '/orders/'
    | '/pick/'
    | '/sort/'
    | '/view-pack/'
    | '/view-picklist/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/agent-directory'
    | '/agent-health'
    | '/alerts'
    | '/approvals'
    | '/audit-log'
    | '/billing-leakage'
    | '/carrier-scorecards'
    | '/control-tower'
    | '/customer-disputes'
    | '/cycle-count'
    | '/dashboard'
    | '/detailed-inventory-view'
    | '/dispatch'
    | '/dock-management'
    | '/drift-feedback'
    | '/floor-handhelds'
    | '/gate-entry'
    | '/gatepass-log'
    | '/grn'
    | '/inbound-exceptions'
    | '/incidents'
    | '/item-info-update'
    | '/item-movement'
    | '/kit-mapping'
    | '/kit-order'
    | '/kitting'
    | '/manifest'
    | '/master-data'
    | '/movement-task-create'
    | '/outbound-exceptions'
    | '/pack'
    | '/policies'
    | '/putaway'
    | '/putwall'
    | '/qc-station'
    | '/recovery-queue'
    | '/replenishment'
    | '/replenishment-setup'
    | '/reports'
    | '/returns-cir'
    | '/returns-evaluation'
    | '/returns-intake'
    | '/returns-rto'
    | '/returns-rtv'
    | '/sales-return-grn'
    | '/site-performance'
    | '/slotting'
    | '/slotting-config'
    | '/stuck-orders'
    | '/trends'
    | '/unloading'
    | '/users-roles'
    | '/vendor-scorecards'
    | '/view-dispatch'
    | '/view-manifest'
    | '/wave-creation'
    | '/orders/$orderNo'
    | '/pick/$picklistId'
    | '/sort/$taskId'
    | '/view-pack/$packlistId'
    | '/view-picklist/$picklistId'
    | '/orders'
    | '/pick'
    | '/sort'
    | '/view-pack'
    | '/view-picklist'
  id:
    | '__root__'
    | '/'
    | '/_wms'
    | '/_wms/admin'
    | '/_wms/agent-directory'
    | '/_wms/agent-health'
    | '/_wms/alerts'
    | '/_wms/approvals'
    | '/_wms/audit-log'
    | '/_wms/billing-leakage'
    | '/_wms/carrier-scorecards'
    | '/_wms/control-tower'
    | '/_wms/customer-disputes'
    | '/_wms/cycle-count'
    | '/_wms/dashboard'
    | '/_wms/detailed-inventory-view'
    | '/_wms/dispatch'
    | '/_wms/dock-management'
    | '/_wms/drift-feedback'
    | '/_wms/floor-handhelds'
    | '/_wms/gate-entry'
    | '/_wms/gatepass-log'
    | '/_wms/grn'
    | '/_wms/inbound-exceptions'
    | '/_wms/incidents'
    | '/_wms/item-info-update'
    | '/_wms/item-movement'
    | '/_wms/kit-mapping'
    | '/_wms/kit-order'
    | '/_wms/kitting'
    | '/_wms/manifest'
    | '/_wms/master-data'
    | '/_wms/movement-task-create'
    | '/_wms/outbound-exceptions'
    | '/_wms/pack'
    | '/_wms/policies'
    | '/_wms/putaway'
    | '/_wms/putwall'
    | '/_wms/qc-station'
    | '/_wms/recovery-queue'
    | '/_wms/replenishment'
    | '/_wms/replenishment-setup'
    | '/_wms/reports'
    | '/_wms/returns-cir'
    | '/_wms/returns-evaluation'
    | '/_wms/returns-intake'
    | '/_wms/returns-rto'
    | '/_wms/returns-rtv'
    | '/_wms/sales-return-grn'
    | '/_wms/site-performance'
    | '/_wms/slotting'
    | '/_wms/slotting-config'
    | '/_wms/stuck-orders'
    | '/_wms/trends'
    | '/_wms/unloading'
    | '/_wms/users-roles'
    | '/_wms/vendor-scorecards'
    | '/_wms/view-dispatch'
    | '/_wms/view-manifest'
    | '/_wms/wave-creation'
    | '/_wms/orders/$orderNo'
    | '/_wms/pick/$picklistId'
    | '/_wms/sort/$taskId'
    | '/_wms/view-pack/$packlistId'
    | '/_wms/view-picklist/$picklistId'
    | '/_wms/orders/'
    | '/_wms/pick/'
    | '/_wms/sort/'
    | '/_wms/view-pack/'
    | '/_wms/view-picklist/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  WmsRoute: typeof WmsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_wms': {
      id: '/_wms'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof WmsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_wms/wave-creation': {
      id: '/_wms/wave-creation'
      path: '/wave-creation'
      fullPath: '/wave-creation'
      preLoaderRoute: typeof WmsWaveCreationRouteImport
      parentRoute: typeof WmsRoute
    }
    '/_wms/view-manifest': {
      id: '/_wms/view-manifest'
      path: '/view-manifest'
      fullPath: '/view-manifest'
      preLoaderRoute: typeof WmsViewManifestRouteImport
      parentRoute: typeof WmsRoute
    }
    '/_wms/view-dispatch': {
      id: '/_wms/view-dispatch'
      path: '/view-dispatch'
      fullPath: '/view-dispatch'
      preLoaderRoute: typeof WmsViewDispatchRouteImport
      parentRoute: typeof WmsRoute
    }
    '/_wms/vendor-scorecards': {
      id: '/_wms/vendor-scorecards'
      path: '/vendor-scorecards'
      fullPath: '/vendor-scorecards'
      preLoaderRoute: typeof WmsVendorScorecardsRouteImport
      parentRoute: typeof WmsRoute
    }
    '/_wms/users-roles': {
      id: '/_wms/users-roles'
      path: '/users-roles'
      fullPath: '/users-roles'
      preLoaderRoute: typeof WmsUsersRolesRouteImport
      parentRoute: typeof WmsRoute
    }
    '/_wms/unloading': {
      id: '/_wms/unloading'
      path: '/unloading'
      fullPath: '/unloading'
      preLoaderRoute: typeof WmsUnloadingRouteImport
      parentRoute: typeof WmsRoute
    }
    '/_wms/trends': {
      id: '/_wms/trends'
      path: '/trends'
      fullPath: '/trends'
      preLoaderRoute: typeof WmsTrendsRouteImport
      parentRoute: typeof WmsRoute
    }
    '/_wms/stuck-orders': {
      id: '/_wms/stuck-orders'
      path: '/stuck-orders'
      fullPath: '/stuck-orders'
      preLoaderRoute: typeof WmsStuckOrdersRouteImport
      parentRoute: typeof WmsRoute
    }
    '/_wms/slotting-config': {
      id: '/_wms/slotting-config'
      path: '/slotting-config'
      fullPath: '/slotting-config'
      preLoaderRoute: typeof WmsSlottingConfigRouteImport
      parentRoute: typeof WmsRoute
    }
    '/_wms/slotting': {
      id: '/_wms/slotting'
      path: '/slotting'
      fullPath: '/slotting'
      preLoaderRoute: typeof WmsSlottingRouteImport
      parentRoute: typeof WmsRoute
    }
    '/_wms/site-performance': {
      id: '/_wms/site-performance'
      path: '/site-performance'
      fullPath: '/site-performance'
      preLoaderRoute: typeof WmsSitePerformanceRouteImport
      parentRoute: typeof WmsRoute
    }
    '/_wms/sales-return-grn': {
      id: '/_wms/sales-return-grn'
      path: '/sales-return-grn'
      fullPath: '/sales-return-grn'
      preLoaderRoute: typeof WmsSalesReturnGrnRouteImport
      parentRoute: typeof WmsRoute
    }
    '/_wms/returns-rtv': {
      id: '/_wms/returns-rtv'
      path: '/returns-rtv'
      fullPath: '/returns-rtv'
      preLoaderRoute: typeof WmsReturnsRtvRouteImport
      parentRoute: typeof WmsRoute
    }
    '/_wms/returns-rto': {
      id: '/_wms/returns-rto'
      path: '/returns-rto'
      fullPath: '/returns-rto'
      preLoaderRoute: typeof WmsReturnsRtoRouteImport
      parentRoute: typeof WmsRoute
    }
    '/_wms/returns-intake': {
      id: '/_wms/returns-intake'
      path: '/returns-intake'
      fullPath: '/returns-intake'
      preLoaderRoute: typeof WmsReturnsIntakeRouteImport
      parentRoute: typeof WmsRoute
    }
    '/_wms/returns-evaluation': {
      id: '/_wms/returns-evaluation'
      path: '/returns-evaluation'
      fullPath: '/returns-evaluation'
      preLoaderRoute: typeof WmsReturnsEvaluationRouteImport
      parentRoute: typeof WmsRoute
    }
    '/_wms/returns-cir': {
      id: '/_wms/returns-cir'
      path: '/returns-cir'
      fullPath: '/returns-cir'
      preLoaderRoute: typeof WmsReturnsCirRouteImport
      parentRoute: typeof WmsRoute
    }
    '/_wms/reports': {
      id: '/_wms/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof WmsReportsRouteImport
      parentRoute: typeof WmsRoute
    }
    '/_wms/replenishment-setup': {
      id: '/_wms/replenishment-setup'
      path: '/replenishment-setup'
      fullPath: '/replenishment-setup'
      preLoaderRoute: typeof WmsReplenishmentSetupRouteImport
      parentRoute: typeof WmsRoute
    }
    '/_wms/replenishment': {
      id: '/_wms/replenishment'
      path: '/replenishment'
      fullPath: '/replenishment'
      preLoaderRoute: typeof WmsReplenishmentRouteImport
      parentRoute: typeof WmsRoute
    }
    '/_wms/recovery-queue': {
      id: '/_wms/recovery-queue'
      path: '/recovery-queue'
      fullPath: '/recovery-queue'
      preLoaderRoute: typeof WmsRecoveryQueueRouteImport
      parentRoute: typeof WmsRoute
    }
    '/_wms/qc-station': {
      id: '/_wms/qc-station'
      path: '/qc-station'
      fullPath: '/qc-station'
      preLoaderRoute: typeof WmsQcStationRouteImport
      parentRoute: typeof WmsRoute
    }
    '/_wms/putwall': {
      id: '/_wms/putwall'
      path: '/putwall'
      fullPath: '/putwall'
      preLoaderRoute: typeof WmsPutwallRouteImport
      parentRoute: typeof WmsRoute
    }
    '/_wms/putaway': {
      id: '/_wms/putaway'
      path: '/putaway'
      fullPath: '/putaway'
      preLoaderRoute: typeof WmsPutawayRouteImport
      parentRoute: typeof WmsRoute
    }
    '/_wms/policies': {
      id: '/_wms/policies'
      path: '/policies'
      fullPath: '/policies'
      preLoaderRoute: typeof WmsPoliciesRouteImport
      parentRoute: typeof WmsRoute
    }
    '/_wms/pack': {
      id: '/_wms/pack'
      path: '/pack'
      fullPath: '/pack'
      preLoaderRoute: typeof WmsPackRouteImport
      parentRoute: typeof WmsRoute
    }
    '/_wms/outbound-exceptions': {
      id: '/_wms/outbound-exceptions'
      path: '/outbound-exceptions'
      fullPath: '/outbound-exceptions'
      preLoaderRoute: typeof WmsOutboundExceptionsRouteImport
      parentRoute: typeof WmsRoute
    }
    '/_wms/movement-task-create': {
      id: '/_wms/movement-task-create'
      path: '/movement-task-create'
      fullPath: '/movement-task-create'
      preLoaderRoute: typeof WmsMovementTaskCreateRouteImport
      parentRoute: typeof WmsRoute
    }
    '/_wms/master-data': {
      id: '/_wms/master-data'
      path: '/master-data'
      fullPath: '/master-data'
      preLoaderRoute: typeof WmsMasterDataRouteImport
      parentRoute: typeof WmsRoute
    }
    '/_wms/manifest': {
      id: '/_wms/manifest'
      path: '/manifest'
      fullPath: '/manifest'
      preLoaderRoute: typeof WmsManifestRouteImport
      parentRoute: typeof WmsRoute
    }
    '/_wms/kitting': {
      id: '/_wms/kitting'
      path: '/kitting'
      fullPath: '/kitting'
      preLoaderRoute: typeof WmsKittingRouteImport
      parentRoute: typeof WmsRoute
    }
    '/_wms/kit-order': {
      id: '/_wms/kit-order'
      path: '/kit-order'
      fullPath: '/kit-order'
      preLoaderRoute: typeof WmsKitOrderRouteImport
      parentRoute: typeof WmsRoute
    }
    '/_wms/kit-mapping': {
      id: '/_wms/kit-mapping'
      path: '/kit-mapping'
      fullPath: '/kit-mapping'
      preLoaderRoute: typeof WmsKitMappingRouteImport
      parentRoute: typeof WmsRoute
    }
    '/_wms/item-movement': {
      id: '/_wms/item-movement'
      path: '/item-movement'
      fullPath: '/item-movement'
      preLoaderRoute: typeof WmsItemMovementRouteImport
      parentRoute: typeof WmsRoute
    }
    '/_wms/item-info-update': {
      id: '/_wms/item-info-update'
      path: '/item-info-update'
      fullPath: '/item-info-update'
      preLoaderRoute: typeof WmsItemInfoUpdateRouteImport
      parentRoute: typeof WmsRoute
    }
    '/_wms/incidents': {
      id: '/_wms/incidents'
      path: '/incidents'
      fullPath: '/incidents'
      preLoaderRoute: typeof WmsIncidentsRouteImport
      parentRoute: typeof WmsRoute
    }
    '/_wms/inbound-exceptions': {
      id: '/_wms/inbound-exceptions'
      path: '/inbound-exceptions'
      fullPath: '/inbound-exceptions'
      preLoaderRoute: typeof WmsInboundExceptionsRouteImport
      parentRoute: typeof WmsRoute
    }
    '/_wms/grn': {
      id: '/_wms/grn'
      path: '/grn'
      fullPath: '/grn'
      preLoaderRoute: typeof WmsGrnRouteImport
      parentRoute: typeof WmsRoute
    }
    '/_wms/gatepass-log': {
      id: '/_wms/gatepass-log'
      path: '/gatepass-log'
      fullPath: '/gatepass-log'
      preLoaderRoute: typeof WmsGatepassLogRouteImport
      parentRoute: typeof WmsRoute
    }
    '/_wms/gate-entry': {
      id: '/_wms/gate-entry'
      path: '/gate-entry'
      fullPath: '/gate-entry'
      preLoaderRoute: typeof WmsGateEntryRouteImport
      parentRoute: typeof WmsRoute
    }
    '/_wms/floor-handhelds': {
      id: '/_wms/floor-handhelds'
      path: '/floor-handhelds'
      fullPath: '/floor-handhelds'
      preLoaderRoute: typeof WmsFloorHandheldsRouteImport
      parentRoute: typeof WmsRoute
    }
    '/_wms/drift-feedback': {
      id: '/_wms/drift-feedback'
      path: '/drift-feedback'
      fullPath: '/drift-feedback'
      preLoaderRoute: typeof WmsDriftFeedbackRouteImport
      parentRoute: typeof WmsRoute
    }
    '/_wms/dock-management': {
      id: '/_wms/dock-management'
      path: '/dock-management'
      fullPath: '/dock-management'
      preLoaderRoute: typeof WmsDockManagementRouteImport
      parentRoute: typeof WmsRoute
    }
    '/_wms/dispatch': {
      id: '/_wms/dispatch'
      path: '/dispatch'
      fullPath: '/dispatch'
      preLoaderRoute: typeof WmsDispatchRouteImport
      parentRoute: typeof WmsRoute
    }
    '/_wms/detailed-inventory-view': {
      id: '/_wms/detailed-inventory-view'
      path: '/detailed-inventory-view'
      fullPath: '/detailed-inventory-view'
      preLoaderRoute: typeof WmsDetailedInventoryViewRouteImport
      parentRoute: typeof WmsRoute
    }
    '/_wms/dashboard': {
      id: '/_wms/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof WmsDashboardRouteImport
      parentRoute: typeof WmsRoute
    }
    '/_wms/cycle-count': {
      id: '/_wms/cycle-count'
      path: '/cycle-count'
      fullPath: '/cycle-count'
      preLoaderRoute: typeof WmsCycleCountRouteImport
      parentRoute: typeof WmsRoute
    }
    '/_wms/customer-disputes': {
      id: '/_wms/customer-disputes'
      path: '/customer-disputes'
      fullPath: '/customer-disputes'
      preLoaderRoute: typeof WmsCustomerDisputesRouteImport
      parentRoute: typeof WmsRoute
    }
    '/_wms/control-tower': {
      id: '/_wms/control-tower'
      path: '/control-tower'
      fullPath: '/control-tower'
      preLoaderRoute: typeof WmsControlTowerRouteImport
      parentRoute: typeof WmsRoute
    }
    '/_wms/carrier-scorecards': {
      id: '/_wms/carrier-scorecards'
      path: '/carrier-scorecards'
      fullPath: '/carrier-scorecards'
      preLoaderRoute: typeof WmsCarrierScorecardsRouteImport
      parentRoute: typeof WmsRoute
    }
    '/_wms/billing-leakage': {
      id: '/_wms/billing-leakage'
      path: '/billing-leakage'
      fullPath: '/billing-leakage'
      preLoaderRoute: typeof WmsBillingLeakageRouteImport
      parentRoute: typeof WmsRoute
    }
    '/_wms/audit-log': {
      id: '/_wms/audit-log'
      path: '/audit-log'
      fullPath: '/audit-log'
      preLoaderRoute: typeof WmsAuditLogRouteImport
      parentRoute: typeof WmsRoute
    }
    '/_wms/approvals': {
      id: '/_wms/approvals'
      path: '/approvals'
      fullPath: '/approvals'
      preLoaderRoute: typeof WmsApprovalsRouteImport
      parentRoute: typeof WmsRoute
    }
    '/_wms/alerts': {
      id: '/_wms/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof WmsAlertsRouteImport
      parentRoute: typeof WmsRoute
    }
    '/_wms/agent-health': {
      id: '/_wms/agent-health'
      path: '/agent-health'
      fullPath: '/agent-health'
      preLoaderRoute: typeof WmsAgentHealthRouteImport
      parentRoute: typeof WmsRoute
    }
    '/_wms/agent-directory': {
      id: '/_wms/agent-directory'
      path: '/agent-directory'
      fullPath: '/agent-directory'
      preLoaderRoute: typeof WmsAgentDirectoryRouteImport
      parentRoute: typeof WmsRoute
    }
    '/_wms/admin': {
      id: '/_wms/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof WmsAdminRouteImport
      parentRoute: typeof WmsRoute
    }
    '/_wms/view-picklist/': {
      id: '/_wms/view-picklist/'
      path: '/view-picklist'
      fullPath: '/view-picklist/'
      preLoaderRoute: typeof WmsViewPicklistIndexRouteImport
      parentRoute: typeof WmsRoute
    }
    '/_wms/view-pack/': {
      id: '/_wms/view-pack/'
      path: '/view-pack'
      fullPath: '/view-pack/'
      preLoaderRoute: typeof WmsViewPackIndexRouteImport
      parentRoute: typeof WmsRoute
    }
    '/_wms/sort/': {
      id: '/_wms/sort/'
      path: '/sort'
      fullPath: '/sort/'
      preLoaderRoute: typeof WmsSortIndexRouteImport
      parentRoute: typeof WmsRoute
    }
    '/_wms/pick/': {
      id: '/_wms/pick/'
      path: '/pick'
      fullPath: '/pick/'
      preLoaderRoute: typeof WmsPickIndexRouteImport
      parentRoute: typeof WmsRoute
    }
    '/_wms/orders/': {
      id: '/_wms/orders/'
      path: '/orders'
      fullPath: '/orders/'
      preLoaderRoute: typeof WmsOrdersIndexRouteImport
      parentRoute: typeof WmsRoute
    }
    '/_wms/view-picklist/$picklistId': {
      id: '/_wms/view-picklist/$picklistId'
      path: '/view-picklist/$picklistId'
      fullPath: '/view-picklist/$picklistId'
      preLoaderRoute: typeof WmsViewPicklistPicklistIdRouteImport
      parentRoute: typeof WmsRoute
    }
    '/_wms/view-pack/$packlistId': {
      id: '/_wms/view-pack/$packlistId'
      path: '/view-pack/$packlistId'
      fullPath: '/view-pack/$packlistId'
      preLoaderRoute: typeof WmsViewPackPacklistIdRouteImport
      parentRoute: typeof WmsRoute
    }
    '/_wms/sort/$taskId': {
      id: '/_wms/sort/$taskId'
      path: '/sort/$taskId'
      fullPath: '/sort/$taskId'
      preLoaderRoute: typeof WmsSortTaskIdRouteImport
      parentRoute: typeof WmsRoute
    }
    '/_wms/pick/$picklistId': {
      id: '/_wms/pick/$picklistId'
      path: '/pick/$picklistId'
      fullPath: '/pick/$picklistId'
      preLoaderRoute: typeof WmsPickPicklistIdRouteImport
      parentRoute: typeof WmsRoute
    }
    '/_wms/orders/$orderNo': {
      id: '/_wms/orders/$orderNo'
      path: '/orders/$orderNo'
      fullPath: '/orders/$orderNo'
      preLoaderRoute: typeof WmsOrdersOrderNoRouteImport
      parentRoute: typeof WmsRoute
    }
  }
}

interface WmsRouteChildren {
  WmsAdminRoute: typeof WmsAdminRoute
  WmsAgentDirectoryRoute: typeof WmsAgentDirectoryRoute
  WmsAgentHealthRoute: typeof WmsAgentHealthRoute
  WmsAlertsRoute: typeof WmsAlertsRoute
  WmsApprovalsRoute: typeof WmsApprovalsRoute
  WmsAuditLogRoute: typeof WmsAuditLogRoute
  WmsBillingLeakageRoute: typeof WmsBillingLeakageRoute
  WmsCarrierScorecardsRoute: typeof WmsCarrierScorecardsRoute
  WmsControlTowerRoute: typeof WmsControlTowerRoute
  WmsCustomerDisputesRoute: typeof WmsCustomerDisputesRoute
  WmsCycleCountRoute: typeof WmsCycleCountRoute
  WmsDashboardRoute: typeof WmsDashboardRoute
  WmsDetailedInventoryViewRoute: typeof WmsDetailedInventoryViewRoute
  WmsDispatchRoute: typeof WmsDispatchRoute
  WmsDockManagementRoute: typeof WmsDockManagementRoute
  WmsDriftFeedbackRoute: typeof WmsDriftFeedbackRoute
  WmsFloorHandheldsRoute: typeof WmsFloorHandheldsRoute
  WmsGateEntryRoute: typeof WmsGateEntryRoute
  WmsGatepassLogRoute: typeof WmsGatepassLogRoute
  WmsGrnRoute: typeof WmsGrnRoute
  WmsInboundExceptionsRoute: typeof WmsInboundExceptionsRoute
  WmsIncidentsRoute: typeof WmsIncidentsRoute
  WmsItemInfoUpdateRoute: typeof WmsItemInfoUpdateRoute
  WmsItemMovementRoute: typeof WmsItemMovementRoute
  WmsKitMappingRoute: typeof WmsKitMappingRoute
  WmsKitOrderRoute: typeof WmsKitOrderRoute
  WmsKittingRoute: typeof WmsKittingRoute
  WmsManifestRoute: typeof WmsManifestRoute
  WmsMasterDataRoute: typeof WmsMasterDataRoute
  WmsMovementTaskCreateRoute: typeof WmsMovementTaskCreateRoute
  WmsOutboundExceptionsRoute: typeof WmsOutboundExceptionsRoute
  WmsPackRoute: typeof WmsPackRoute
  WmsPoliciesRoute: typeof WmsPoliciesRoute
  WmsPutawayRoute: typeof WmsPutawayRoute
  WmsPutwallRoute: typeof WmsPutwallRoute
  WmsQcStationRoute: typeof WmsQcStationRoute
  WmsRecoveryQueueRoute: typeof WmsRecoveryQueueRoute
  WmsReplenishmentRoute: typeof WmsReplenishmentRoute
  WmsReplenishmentSetupRoute: typeof WmsReplenishmentSetupRoute
  WmsReportsRoute: typeof WmsReportsRoute
  WmsReturnsCirRoute: typeof WmsReturnsCirRoute
  WmsReturnsEvaluationRoute: typeof WmsReturnsEvaluationRoute
  WmsReturnsIntakeRoute: typeof WmsReturnsIntakeRoute
  WmsReturnsRtoRoute: typeof WmsReturnsRtoRoute
  WmsReturnsRtvRoute: typeof WmsReturnsRtvRoute
  WmsSalesReturnGrnRoute: typeof WmsSalesReturnGrnRoute
  WmsSitePerformanceRoute: typeof WmsSitePerformanceRoute
  WmsSlottingRoute: typeof WmsSlottingRoute
  WmsSlottingConfigRoute: typeof WmsSlottingConfigRoute
  WmsStuckOrdersRoute: typeof WmsStuckOrdersRoute
  WmsTrendsRoute: typeof WmsTrendsRoute
  WmsUnloadingRoute: typeof WmsUnloadingRoute
  WmsUsersRolesRoute: typeof WmsUsersRolesRoute
  WmsVendorScorecardsRoute: typeof WmsVendorScorecardsRoute
  WmsViewDispatchRoute: typeof WmsViewDispatchRoute
  WmsViewManifestRoute: typeof WmsViewManifestRoute
  WmsWaveCreationRoute: typeof WmsWaveCreationRoute
  WmsOrdersOrderNoRoute: typeof WmsOrdersOrderNoRoute
  WmsPickPicklistIdRoute: typeof WmsPickPicklistIdRoute
  WmsSortTaskIdRoute: typeof WmsSortTaskIdRoute
  WmsViewPackPacklistIdRoute: typeof WmsViewPackPacklistIdRoute
  WmsViewPicklistPicklistIdRoute: typeof WmsViewPicklistPicklistIdRoute
  WmsOrdersIndexRoute: typeof WmsOrdersIndexRoute
  WmsPickIndexRoute: typeof WmsPickIndexRoute
  WmsSortIndexRoute: typeof WmsSortIndexRoute
  WmsViewPackIndexRoute: typeof WmsViewPackIndexRoute
  WmsViewPicklistIndexRoute: typeof WmsViewPicklistIndexRoute
}

const WmsRouteChildren: WmsRouteChildren = {
  WmsAdminRoute: WmsAdminRoute,
  WmsAgentDirectoryRoute: WmsAgentDirectoryRoute,
  WmsAgentHealthRoute: WmsAgentHealthRoute,
  WmsAlertsRoute: WmsAlertsRoute,
  WmsApprovalsRoute: WmsApprovalsRoute,
  WmsAuditLogRoute: WmsAuditLogRoute,
  WmsBillingLeakageRoute: WmsBillingLeakageRoute,
  WmsCarrierScorecardsRoute: WmsCarrierScorecardsRoute,
  WmsControlTowerRoute: WmsControlTowerRoute,
  WmsCustomerDisputesRoute: WmsCustomerDisputesRoute,
  WmsCycleCountRoute: WmsCycleCountRoute,
  WmsDashboardRoute: WmsDashboardRoute,
  WmsDetailedInventoryViewRoute: WmsDetailedInventoryViewRoute,
  WmsDispatchRoute: WmsDispatchRoute,
  WmsDockManagementRoute: WmsDockManagementRoute,
  WmsDriftFeedbackRoute: WmsDriftFeedbackRoute,
  WmsFloorHandheldsRoute: WmsFloorHandheldsRoute,
  WmsGateEntryRoute: WmsGateEntryRoute,
  WmsGatepassLogRoute: WmsGatepassLogRoute,
  WmsGrnRoute: WmsGrnRoute,
  WmsInboundExceptionsRoute: WmsInboundExceptionsRoute,
  WmsIncidentsRoute: WmsIncidentsRoute,
  WmsItemInfoUpdateRoute: WmsItemInfoUpdateRoute,
  WmsItemMovementRoute: WmsItemMovementRoute,
  WmsKitMappingRoute: WmsKitMappingRoute,
  WmsKitOrderRoute: WmsKitOrderRoute,
  WmsKittingRoute: WmsKittingRoute,
  WmsManifestRoute: WmsManifestRoute,
  WmsMasterDataRoute: WmsMasterDataRoute,
  WmsMovementTaskCreateRoute: WmsMovementTaskCreateRoute,
  WmsOutboundExceptionsRoute: WmsOutboundExceptionsRoute,
  WmsPackRoute: WmsPackRoute,
  WmsPoliciesRoute: WmsPoliciesRoute,
  WmsPutawayRoute: WmsPutawayRoute,
  WmsPutwallRoute: WmsPutwallRoute,
  WmsQcStationRoute: WmsQcStationRoute,
  WmsRecoveryQueueRoute: WmsRecoveryQueueRoute,
  WmsReplenishmentRoute: WmsReplenishmentRoute,
  WmsReplenishmentSetupRoute: WmsReplenishmentSetupRoute,
  WmsReportsRoute: WmsReportsRoute,
  WmsReturnsCirRoute: WmsReturnsCirRoute,
  WmsReturnsEvaluationRoute: WmsReturnsEvaluationRoute,
  WmsReturnsIntakeRoute: WmsReturnsIntakeRoute,
  WmsReturnsRtoRoute: WmsReturnsRtoRoute,
  WmsReturnsRtvRoute: WmsReturnsRtvRoute,
  WmsSalesReturnGrnRoute: WmsSalesReturnGrnRoute,
  WmsSitePerformanceRoute: WmsSitePerformanceRoute,
  WmsSlottingRoute: WmsSlottingRoute,
  WmsSlottingConfigRoute: WmsSlottingConfigRoute,
  WmsStuckOrdersRoute: WmsStuckOrdersRoute,
  WmsTrendsRoute: WmsTrendsRoute,
  WmsUnloadingRoute: WmsUnloadingRoute,
  WmsUsersRolesRoute: WmsUsersRolesRoute,
  WmsVendorScorecardsRoute: WmsVendorScorecardsRoute,
  WmsViewDispatchRoute: WmsViewDispatchRoute,
  WmsViewManifestRoute: WmsViewManifestRoute,
  WmsWaveCreationRoute: WmsWaveCreationRoute,
  WmsOrdersOrderNoRoute: WmsOrdersOrderNoRoute,
  WmsPickPicklistIdRoute: WmsPickPicklistIdRoute,
  WmsSortTaskIdRoute: WmsSortTaskIdRoute,
  WmsViewPackPacklistIdRoute: WmsViewPackPacklistIdRoute,
  WmsViewPicklistPicklistIdRoute: WmsViewPicklistPicklistIdRoute,
  WmsOrdersIndexRoute: WmsOrdersIndexRoute,
  WmsPickIndexRoute: WmsPickIndexRoute,
  WmsSortIndexRoute: WmsSortIndexRoute,
  WmsViewPackIndexRoute: WmsViewPackIndexRoute,
  WmsViewPicklistIndexRoute: WmsViewPicklistIndexRoute,
}

const WmsRouteWithChildren = WmsRoute._addFileChildren(WmsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  WmsRoute: WmsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
