/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WmsRouteImport } from './routes/_wms'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WmsUnloadingRouteImport } from './routes/_wms.unloading'
import { Route as WmsPutwallRouteImport } from './routes/_wms.putwall'
import { Route as WmsPutawayRouteImport } from './routes/_wms.putaway'
import { Route as WmsPackRouteImport } from './routes/_wms.pack'
import { Route as WmsManifestRouteImport } from './routes/_wms.manifest'
import { Route as WmsGrnRouteImport } from './routes/_wms.grn'
import { Route as WmsGateEntryRouteImport } from './routes/_wms.gate-entry'
import { Route as WmsDispatchRouteImport } from './routes/_wms.dispatch'
import { Route as WmsSortIndexRouteImport } from './routes/_wms.sort.index'
import { Route as WmsPickIndexRouteImport } from './routes/_wms.pick.index'
import { Route as WmsOrdersIndexRouteImport } from './routes/_wms.orders.index'
import { Route as WmsSortTaskIdRouteImport } from './routes/_wms.sort.$taskId'
import { Route as WmsPickPicklistIdRouteImport } from './routes/_wms.pick.$picklistId'
import { Route as WmsOrdersOrderNoRouteImport } from './routes/_wms.orders.$orderNo'

const WmsRoute = WmsRouteImport.update({
  id: '/_wms',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WmsUnloadingRoute = WmsUnloadingRouteImport.update({
  id: '/unloading',
  path: '/unloading',
  getParentRoute: () => WmsRoute,
} as any)
const WmsPutwallRoute = WmsPutwallRouteImport.update({
  id: '/putwall',
  path: '/putwall',
  getParentRoute: () => WmsRoute,
} as any)
const WmsPutawayRoute = WmsPutawayRouteImport.update({
  id: '/putaway',
  path: '/putaway',
  getParentRoute: () => WmsRoute,
} as any)
const WmsPackRoute = WmsPackRouteImport.update({
  id: '/pack',
  path: '/pack',
  getParentRoute: () => WmsRoute,
} as any)
const WmsManifestRoute = WmsManifestRouteImport.update({
  id: '/manifest',
  path: '/manifest',
  getParentRoute: () => WmsRoute,
} as any)
const WmsGrnRoute = WmsGrnRouteImport.update({
  id: '/grn',
  path: '/grn',
  getParentRoute: () => WmsRoute,
} as any)
const WmsGateEntryRoute = WmsGateEntryRouteImport.update({
  id: '/gate-entry',
  path: '/gate-entry',
  getParentRoute: () => WmsRoute,
} as any)
const WmsDispatchRoute = WmsDispatchRouteImport.update({
  id: '/dispatch',
  path: '/dispatch',
  getParentRoute: () => WmsRoute,
} as any)
const WmsSortIndexRoute = WmsSortIndexRouteImport.update({
  id: '/sort/',
  path: '/sort/',
  getParentRoute: () => WmsRoute,
} as any)
const WmsPickIndexRoute = WmsPickIndexRouteImport.update({
  id: '/pick/',
  path: '/pick/',
  getParentRoute: () => WmsRoute,
} as any)
const WmsOrdersIndexRoute = WmsOrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => WmsRoute,
} as any)
const WmsSortTaskIdRoute = WmsSortTaskIdRouteImport.update({
  id: '/sort/$taskId',
  path: '/sort/$taskId',
  getParentRoute: () => WmsRoute,
} as any)
const WmsPickPicklistIdRoute = WmsPickPicklistIdRouteImport.update({
  id: '/pick/$picklistId',
  path: '/pick/$picklistId',
  getParentRoute: () => WmsRoute,
} as any)
const WmsOrdersOrderNoRoute = WmsOrdersOrderNoRouteImport.update({
  id: '/orders/$orderNo',
  path: '/orders/$orderNo',
  getParentRoute: () => WmsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dispatch': typeof WmsDispatchRoute
  '/gate-entry': typeof WmsGateEntryRoute
  '/grn': typeof WmsGrnRoute
  '/manifest': typeof WmsManifestRoute
  '/pack': typeof WmsPackRoute
  '/putaway': typeof WmsPutawayRoute
  '/putwall': typeof WmsPutwallRoute
  '/unloading': typeof WmsUnloadingRoute
  '/orders/$orderNo': typeof WmsOrdersOrderNoRoute
  '/pick/$picklistId': typeof WmsPickPicklistIdRoute
  '/sort/$taskId': typeof WmsSortTaskIdRoute
  '/orders/': typeof WmsOrdersIndexRoute
  '/pick/': typeof WmsPickIndexRoute
  '/sort/': typeof WmsSortIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dispatch': typeof WmsDispatchRoute
  '/gate-entry': typeof WmsGateEntryRoute
  '/grn': typeof WmsGrnRoute
  '/manifest': typeof WmsManifestRoute
  '/pack': typeof WmsPackRoute
  '/putaway': typeof WmsPutawayRoute
  '/putwall': typeof WmsPutwallRoute
  '/unloading': typeof WmsUnloadingRoute
  '/orders/$orderNo': typeof WmsOrdersOrderNoRoute
  '/pick/$picklistId': typeof WmsPickPicklistIdRoute
  '/sort/$taskId': typeof WmsSortTaskIdRoute
  '/orders': typeof WmsOrdersIndexRoute
  '/pick': typeof WmsPickIndexRoute
  '/sort': typeof WmsSortIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_wms': typeof WmsRouteWithChildren
  '/_wms/dispatch': typeof WmsDispatchRoute
  '/_wms/gate-entry': typeof WmsGateEntryRoute
  '/_wms/grn': typeof WmsGrnRoute
  '/_wms/manifest': typeof WmsManifestRoute
  '/_wms/pack': typeof WmsPackRoute
  '/_wms/putaway': typeof WmsPutawayRoute
  '/_wms/putwall': typeof WmsPutwallRoute
  '/_wms/unloading': typeof WmsUnloadingRoute
  '/_wms/orders/$orderNo': typeof WmsOrdersOrderNoRoute
  '/_wms/pick/$picklistId': typeof WmsPickPicklistIdRoute
  '/_wms/sort/$taskId': typeof WmsSortTaskIdRoute
  '/_wms/orders/': typeof WmsOrdersIndexRoute
  '/_wms/pick/': typeof WmsPickIndexRoute
  '/_wms/sort/': typeof WmsSortIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dispatch'
    | '/gate-entry'
    | '/grn'
    | '/manifest'
    | '/pack'
    | '/putaway'
    | '/putwall'
    | '/unloading'
    | '/orders/$orderNo'
    | '/pick/$picklistId'
    | '/sort/$taskId'
    | '/orders/'
    | '/pick/'
    | '/sort/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dispatch'
    | '/gate-entry'
    | '/grn'
    | '/manifest'
    | '/pack'
    | '/putaway'
    | '/putwall'
    | '/unloading'
    | '/orders/$orderNo'
    | '/pick/$picklistId'
    | '/sort/$taskId'
    | '/orders'
    | '/pick'
    | '/sort'
  id:
    | '__root__'
    | '/'
    | '/_wms'
    | '/_wms/dispatch'
    | '/_wms/gate-entry'
    | '/_wms/grn'
    | '/_wms/manifest'
    | '/_wms/pack'
    | '/_wms/putaway'
    | '/_wms/putwall'
    | '/_wms/unloading'
    | '/_wms/orders/$orderNo'
    | '/_wms/pick/$picklistId'
    | '/_wms/sort/$taskId'
    | '/_wms/orders/'
    | '/_wms/pick/'
    | '/_wms/sort/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  WmsRoute: typeof WmsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_wms': {
      id: '/_wms'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof WmsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_wms/unloading': {
      id: '/_wms/unloading'
      path: '/unloading'
      fullPath: '/unloading'
      preLoaderRoute: typeof WmsUnloadingRouteImport
      parentRoute: typeof WmsRoute
    }
    '/_wms/putwall': {
      id: '/_wms/putwall'
      path: '/putwall'
      fullPath: '/putwall'
      preLoaderRoute: typeof WmsPutwallRouteImport
      parentRoute: typeof WmsRoute
    }
    '/_wms/putaway': {
      id: '/_wms/putaway'
      path: '/putaway'
      fullPath: '/putaway'
      preLoaderRoute: typeof WmsPutawayRouteImport
      parentRoute: typeof WmsRoute
    }
    '/_wms/pack': {
      id: '/_wms/pack'
      path: '/pack'
      fullPath: '/pack'
      preLoaderRoute: typeof WmsPackRouteImport
      parentRoute: typeof WmsRoute
    }
    '/_wms/manifest': {
      id: '/_wms/manifest'
      path: '/manifest'
      fullPath: '/manifest'
      preLoaderRoute: typeof WmsManifestRouteImport
      parentRoute: typeof WmsRoute
    }
    '/_wms/grn': {
      id: '/_wms/grn'
      path: '/grn'
      fullPath: '/grn'
      preLoaderRoute: typeof WmsGrnRouteImport
      parentRoute: typeof WmsRoute
    }
    '/_wms/gate-entry': {
      id: '/_wms/gate-entry'
      path: '/gate-entry'
      fullPath: '/gate-entry'
      preLoaderRoute: typeof WmsGateEntryRouteImport
      parentRoute: typeof WmsRoute
    }
    '/_wms/dispatch': {
      id: '/_wms/dispatch'
      path: '/dispatch'
      fullPath: '/dispatch'
      preLoaderRoute: typeof WmsDispatchRouteImport
      parentRoute: typeof WmsRoute
    }
    '/_wms/sort/': {
      id: '/_wms/sort/'
      path: '/sort'
      fullPath: '/sort/'
      preLoaderRoute: typeof WmsSortIndexRouteImport
      parentRoute: typeof WmsRoute
    }
    '/_wms/pick/': {
      id: '/_wms/pick/'
      path: '/pick'
      fullPath: '/pick/'
      preLoaderRoute: typeof WmsPickIndexRouteImport
      parentRoute: typeof WmsRoute
    }
    '/_wms/orders/': {
      id: '/_wms/orders/'
      path: '/orders'
      fullPath: '/orders/'
      preLoaderRoute: typeof WmsOrdersIndexRouteImport
      parentRoute: typeof WmsRoute
    }
    '/_wms/sort/$taskId': {
      id: '/_wms/sort/$taskId'
      path: '/sort/$taskId'
      fullPath: '/sort/$taskId'
      preLoaderRoute: typeof WmsSortTaskIdRouteImport
      parentRoute: typeof WmsRoute
    }
    '/_wms/pick/$picklistId': {
      id: '/_wms/pick/$picklistId'
      path: '/pick/$picklistId'
      fullPath: '/pick/$picklistId'
      preLoaderRoute: typeof WmsPickPicklistIdRouteImport
      parentRoute: typeof WmsRoute
    }
    '/_wms/orders/$orderNo': {
      id: '/_wms/orders/$orderNo'
      path: '/orders/$orderNo'
      fullPath: '/orders/$orderNo'
      preLoaderRoute: typeof WmsOrdersOrderNoRouteImport
      parentRoute: typeof WmsRoute
    }
  }
}

interface WmsRouteChildren {
  WmsDispatchRoute: typeof WmsDispatchRoute
  WmsGateEntryRoute: typeof WmsGateEntryRoute
  WmsGrnRoute: typeof WmsGrnRoute
  WmsManifestRoute: typeof WmsManifestRoute
  WmsPackRoute: typeof WmsPackRoute
  WmsPutawayRoute: typeof WmsPutawayRoute
  WmsPutwallRoute: typeof WmsPutwallRoute
  WmsUnloadingRoute: typeof WmsUnloadingRoute
  WmsOrdersOrderNoRoute: typeof WmsOrdersOrderNoRoute
  WmsPickPicklistIdRoute: typeof WmsPickPicklistIdRoute
  WmsSortTaskIdRoute: typeof WmsSortTaskIdRoute
  WmsOrdersIndexRoute: typeof WmsOrdersIndexRoute
  WmsPickIndexRoute: typeof WmsPickIndexRoute
  WmsSortIndexRoute: typeof WmsSortIndexRoute
}

const WmsRouteChildren: WmsRouteChildren = {
  WmsDispatchRoute: WmsDispatchRoute,
  WmsGateEntryRoute: WmsGateEntryRoute,
  WmsGrnRoute: WmsGrnRoute,
  WmsManifestRoute: WmsManifestRoute,
  WmsPackRoute: WmsPackRoute,
  WmsPutawayRoute: WmsPutawayRoute,
  WmsPutwallRoute: WmsPutwallRoute,
  WmsUnloadingRoute: WmsUnloadingRoute,
  WmsOrdersOrderNoRoute: WmsOrdersOrderNoRoute,
  WmsPickPicklistIdRoute: WmsPickPicklistIdRoute,
  WmsSortTaskIdRoute: WmsSortTaskIdRoute,
  WmsOrdersIndexRoute: WmsOrdersIndexRoute,
  WmsPickIndexRoute: WmsPickIndexRoute,
  WmsSortIndexRoute: WmsSortIndexRoute,
}

const WmsRouteWithChildren = WmsRoute._addFileChildren(WmsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  WmsRoute: WmsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
