/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WmsRouteImport } from './routes/_wms'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WmsWaveCreationRouteImport } from './routes/_wms.wave-creation'
import { Route as WmsViewManifestRouteImport } from './routes/_wms.view-manifest'
import { Route as WmsViewDispatchRouteImport } from './routes/_wms.view-dispatch'
import { Route as WmsUnloadingRouteImport } from './routes/_wms.unloading'
import { Route as WmsSlottingConfigRouteImport } from './routes/_wms.slotting-config'
import { Route as WmsSlottingRouteImport } from './routes/_wms.slotting'
import { Route as WmsSalesReturnGrnRouteImport } from './routes/_wms.sales-return-grn'
import { Route as WmsReportsRouteImport } from './routes/_wms.reports'
import { Route as WmsReplenishmentSetupRouteImport } from './routes/_wms.replenishment-setup'
import { Route as WmsReplenishmentRouteImport } from './routes/_wms.replenishment'
import { Route as WmsPutwallRouteImport } from './routes/_wms.putwall'
import { Route as WmsPutawayRouteImport } from './routes/_wms.putaway'
import { Route as WmsPackRouteImport } from './routes/_wms.pack'
import { Route as WmsMovementTaskCreateRouteImport } from './routes/_wms.movement-task-create'
import { Route as WmsManifestRouteImport } from './routes/_wms.manifest'
import { Route as WmsKittingRouteImport } from './routes/_wms.kitting'
import { Route as WmsKitOrderRouteImport } from './routes/_wms.kit-order'
import { Route as WmsKitMappingRouteImport } from './routes/_wms.kit-mapping'
import { Route as WmsItemMovementRouteImport } from './routes/_wms.item-movement'
import { Route as WmsItemInfoUpdateRouteImport } from './routes/_wms.item-info-update'
import { Route as WmsGrnRouteImport } from './routes/_wms.grn'
import { Route as WmsGateEntryRouteImport } from './routes/_wms.gate-entry'
import { Route as WmsDockManagementRouteImport } from './routes/_wms.dock-management'
import { Route as WmsDispatchRouteImport } from './routes/_wms.dispatch'
import { Route as WmsDetailedInventoryViewRouteImport } from './routes/_wms.detailed-inventory-view'
import { Route as WmsApprovalsRouteImport } from './routes/_wms.approvals'
import { Route as WmsViewPicklistIndexRouteImport } from './routes/_wms.view-picklist.index'
import { Route as WmsViewPackIndexRouteImport } from './routes/_wms.view-pack.index'
import { Route as WmsSortIndexRouteImport } from './routes/_wms.sort.index'
import { Route as WmsPickIndexRouteImport } from './routes/_wms.pick.index'
import { Route as WmsOrdersIndexRouteImport } from './routes/_wms.orders.index'
import { Route as WmsViewPicklistPicklistIdRouteImport } from './routes/_wms.view-picklist.$picklistId'
import { Route as WmsViewPackPacklistIdRouteImport } from './routes/_wms.view-pack.$packlistId'
import { Route as WmsSortTaskIdRouteImport } from './routes/_wms.sort.$taskId'
import { Route as WmsPickPicklistIdRouteImport } from './routes/_wms.pick.$picklistId'
import { Route as WmsOrdersOrderNoRouteImport } from './routes/_wms.orders.$orderNo'

const WmsRoute = WmsRouteImport.update({
  id: '/_wms',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WmsWaveCreationRoute = WmsWaveCreationRouteImport.update({
  id: '/wave-creation',
  path: '/wave-creation',
  getParentRoute: () => WmsRoute,
} as any)
const WmsViewManifestRoute = WmsViewManifestRouteImport.update({
  id: '/view-manifest',
  path: '/view-manifest',
  getParentRoute: () => WmsRoute,
} as any)
const WmsViewDispatchRoute = WmsViewDispatchRouteImport.update({
  id: '/view-dispatch',
  path: '/view-dispatch',
  getParentRoute: () => WmsRoute,
} as any)
const WmsUnloadingRoute = WmsUnloadingRouteImport.update({
  id: '/unloading',
  path: '/unloading',
  getParentRoute: () => WmsRoute,
} as any)
const WmsSlottingConfigRoute = WmsSlottingConfigRouteImport.update({
  id: '/slotting-config',
  path: '/slotting-config',
  getParentRoute: () => WmsRoute,
} as any)
const WmsSlottingRoute = WmsSlottingRouteImport.update({
  id: '/slotting',
  path: '/slotting',
  getParentRoute: () => WmsRoute,
} as any)
const WmsSalesReturnGrnRoute = WmsSalesReturnGrnRouteImport.update({
  id: '/sales-return-grn',
  path: '/sales-return-grn',
  getParentRoute: () => WmsRoute,
} as any)
const WmsReportsRoute = WmsReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => WmsRoute,
} as any)
const WmsReplenishmentSetupRoute = WmsReplenishmentSetupRouteImport.update({
  id: '/replenishment-setup',
  path: '/replenishment-setup',
  getParentRoute: () => WmsRoute,
} as any)
const WmsReplenishmentRoute = WmsReplenishmentRouteImport.update({
  id: '/replenishment',
  path: '/replenishment',
  getParentRoute: () => WmsRoute,
} as any)
const WmsPutwallRoute = WmsPutwallRouteImport.update({
  id: '/putwall',
  path: '/putwall',
  getParentRoute: () => WmsRoute,
} as any)
const WmsPutawayRoute = WmsPutawayRouteImport.update({
  id: '/putaway',
  path: '/putaway',
  getParentRoute: () => WmsRoute,
} as any)
const WmsPackRoute = WmsPackRouteImport.update({
  id: '/pack',
  path: '/pack',
  getParentRoute: () => WmsRoute,
} as any)
const WmsMovementTaskCreateRoute = WmsMovementTaskCreateRouteImport.update({
  id: '/movement-task-create',
  path: '/movement-task-create',
  getParentRoute: () => WmsRoute,
} as any)
const WmsManifestRoute = WmsManifestRouteImport.update({
  id: '/manifest',
  path: '/manifest',
  getParentRoute: () => WmsRoute,
} as any)
const WmsKittingRoute = WmsKittingRouteImport.update({
  id: '/kitting',
  path: '/kitting',
  getParentRoute: () => WmsRoute,
} as any)
const WmsKitOrderRoute = WmsKitOrderRouteImport.update({
  id: '/kit-order',
  path: '/kit-order',
  getParentRoute: () => WmsRoute,
} as any)
const WmsKitMappingRoute = WmsKitMappingRouteImport.update({
  id: '/kit-mapping',
  path: '/kit-mapping',
  getParentRoute: () => WmsRoute,
} as any)
const WmsItemMovementRoute = WmsItemMovementRouteImport.update({
  id: '/item-movement',
  path: '/item-movement',
  getParentRoute: () => WmsRoute,
} as any)
const WmsItemInfoUpdateRoute = WmsItemInfoUpdateRouteImport.update({
  id: '/item-info-update',
  path: '/item-info-update',
  getParentRoute: () => WmsRoute,
} as any)
const WmsGrnRoute = WmsGrnRouteImport.update({
  id: '/grn',
  path: '/grn',
  getParentRoute: () => WmsRoute,
} as any)
const WmsGateEntryRoute = WmsGateEntryRouteImport.update({
  id: '/gate-entry',
  path: '/gate-entry',
  getParentRoute: () => WmsRoute,
} as any)
const WmsDockManagementRoute = WmsDockManagementRouteImport.update({
  id: '/dock-management',
  path: '/dock-management',
  getParentRoute: () => WmsRoute,
} as any)
const WmsDispatchRoute = WmsDispatchRouteImport.update({
  id: '/dispatch',
  path: '/dispatch',
  getParentRoute: () => WmsRoute,
} as any)
const WmsDetailedInventoryViewRoute =
  WmsDetailedInventoryViewRouteImport.update({
    id: '/detailed-inventory-view',
    path: '/detailed-inventory-view',
    getParentRoute: () => WmsRoute,
  } as any)
const WmsApprovalsRoute = WmsApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => WmsRoute,
} as any)
const WmsViewPicklistIndexRoute = WmsViewPicklistIndexRouteImport.update({
  id: '/view-picklist/',
  path: '/view-picklist/',
  getParentRoute: () => WmsRoute,
} as any)
const WmsViewPackIndexRoute = WmsViewPackIndexRouteImport.update({
  id: '/view-pack/',
  path: '/view-pack/',
  getParentRoute: () => WmsRoute,
} as any)
const WmsSortIndexRoute = WmsSortIndexRouteImport.update({
  id: '/sort/',
  path: '/sort/',
  getParentRoute: () => WmsRoute,
} as any)
const WmsPickIndexRoute = WmsPickIndexRouteImport.update({
  id: '/pick/',
  path: '/pick/',
  getParentRoute: () => WmsRoute,
} as any)
const WmsOrdersIndexRoute = WmsOrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => WmsRoute,
} as any)
const WmsViewPicklistPicklistIdRoute =
  WmsViewPicklistPicklistIdRouteImport.update({
    id: '/view-picklist/$picklistId',
    path: '/view-picklist/$picklistId',
    getParentRoute: () => WmsRoute,
  } as any)
const WmsViewPackPacklistIdRoute = WmsViewPackPacklistIdRouteImport.update({
  id: '/view-pack/$packlistId',
  path: '/view-pack/$packlistId',
  getParentRoute: () => WmsRoute,
} as any)
const WmsSortTaskIdRoute = WmsSortTaskIdRouteImport.update({
  id: '/sort/$taskId',
  path: '/sort/$taskId',
  getParentRoute: () => WmsRoute,
} as any)
const WmsPickPicklistIdRoute = WmsPickPicklistIdRouteImport.update({
  id: '/pick/$picklistId',
  path: '/pick/$picklistId',
  getParentRoute: () => WmsRoute,
} as any)
const WmsOrdersOrderNoRoute = WmsOrdersOrderNoRouteImport.update({
  id: '/orders/$orderNo',
  path: '/orders/$orderNo',
  getParentRoute: () => WmsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/approvals': typeof WmsApprovalsRoute
  '/detailed-inventory-view': typeof WmsDetailedInventoryViewRoute
  '/dispatch': typeof WmsDispatchRoute
  '/dock-management': typeof WmsDockManagementRoute
  '/gate-entry': typeof WmsGateEntryRoute
  '/grn': typeof WmsGrnRoute
  '/item-info-update': typeof WmsItemInfoUpdateRoute
  '/item-movement': typeof WmsItemMovementRoute
  '/kit-mapping': typeof WmsKitMappingRoute
  '/kit-order': typeof WmsKitOrderRoute
  '/kitting': typeof WmsKittingRoute
  '/manifest': typeof WmsManifestRoute
  '/movement-task-create': typeof WmsMovementTaskCreateRoute
  '/pack': typeof WmsPackRoute
  '/putaway': typeof WmsPutawayRoute
  '/putwall': typeof WmsPutwallRoute
  '/replenishment': typeof WmsReplenishmentRoute
  '/replenishment-setup': typeof WmsReplenishmentSetupRoute
  '/reports': typeof WmsReportsRoute
  '/sales-return-grn': typeof WmsSalesReturnGrnRoute
  '/slotting': typeof WmsSlottingRoute
  '/slotting-config': typeof WmsSlottingConfigRoute
  '/unloading': typeof WmsUnloadingRoute
  '/view-dispatch': typeof WmsViewDispatchRoute
  '/view-manifest': typeof WmsViewManifestRoute
  '/wave-creation': typeof WmsWaveCreationRoute
  '/orders/$orderNo': typeof WmsOrdersOrderNoRoute
  '/pick/$picklistId': typeof WmsPickPicklistIdRoute
  '/sort/$taskId': typeof WmsSortTaskIdRoute
  '/view-pack/$packlistId': typeof WmsViewPackPacklistIdRoute
  '/view-picklist/$picklistId': typeof WmsViewPicklistPicklistIdRoute
  '/orders/': typeof WmsOrdersIndexRoute
  '/pick/': typeof WmsPickIndexRoute
  '/sort/': typeof WmsSortIndexRoute
  '/view-pack/': typeof WmsViewPackIndexRoute
  '/view-picklist/': typeof WmsViewPicklistIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/approvals': typeof WmsApprovalsRoute
  '/detailed-inventory-view': typeof WmsDetailedInventoryViewRoute
  '/dispatch': typeof WmsDispatchRoute
  '/dock-management': typeof WmsDockManagementRoute
  '/gate-entry': typeof WmsGateEntryRoute
  '/grn': typeof WmsGrnRoute
  '/item-info-update': typeof WmsItemInfoUpdateRoute
  '/item-movement': typeof WmsItemMovementRoute
  '/kit-mapping': typeof WmsKitMappingRoute
  '/kit-order': typeof WmsKitOrderRoute
  '/kitting': typeof WmsKittingRoute
  '/manifest': typeof WmsManifestRoute
  '/movement-task-create': typeof WmsMovementTaskCreateRoute
  '/pack': typeof WmsPackRoute
  '/putaway': typeof WmsPutawayRoute
  '/putwall': typeof WmsPutwallRoute
  '/replenishment': typeof WmsReplenishmentRoute
  '/replenishment-setup': typeof WmsReplenishmentSetupRoute
  '/reports': typeof WmsReportsRoute
  '/sales-return-grn': typeof WmsSalesReturnGrnRoute
  '/slotting': typeof WmsSlottingRoute
  '/slotting-config': typeof WmsSlottingConfigRoute
  '/unloading': typeof WmsUnloadingRoute
  '/view-dispatch': typeof WmsViewDispatchRoute
  '/view-manifest': typeof WmsViewManifestRoute
  '/wave-creation': typeof WmsWaveCreationRoute
  '/orders/$orderNo': typeof WmsOrdersOrderNoRoute
  '/pick/$picklistId': typeof WmsPickPicklistIdRoute
  '/sort/$taskId': typeof WmsSortTaskIdRoute
  '/view-pack/$packlistId': typeof WmsViewPackPacklistIdRoute
  '/view-picklist/$picklistId': typeof WmsViewPicklistPicklistIdRoute
  '/orders': typeof WmsOrdersIndexRoute
  '/pick': typeof WmsPickIndexRoute
  '/sort': typeof WmsSortIndexRoute
  '/view-pack': typeof WmsViewPackIndexRoute
  '/view-picklist': typeof WmsViewPicklistIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_wms': typeof WmsRouteWithChildren
  '/_wms/approvals': typeof WmsApprovalsRoute
  '/_wms/detailed-inventory-view': typeof WmsDetailedInventoryViewRoute
  '/_wms/dispatch': typeof WmsDispatchRoute
  '/_wms/dock-management': typeof WmsDockManagementRoute
  '/_wms/gate-entry': typeof WmsGateEntryRoute
  '/_wms/grn': typeof WmsGrnRoute
  '/_wms/item-info-update': typeof WmsItemInfoUpdateRoute
  '/_wms/item-movement': typeof WmsItemMovementRoute
  '/_wms/kit-mapping': typeof WmsKitMappingRoute
  '/_wms/kit-order': typeof WmsKitOrderRoute
  '/_wms/kitting': typeof WmsKittingRoute
  '/_wms/manifest': typeof WmsManifestRoute
  '/_wms/movement-task-create': typeof WmsMovementTaskCreateRoute
  '/_wms/pack': typeof WmsPackRoute
  '/_wms/putaway': typeof WmsPutawayRoute
  '/_wms/putwall': typeof WmsPutwallRoute
  '/_wms/replenishment': typeof WmsReplenishmentRoute
  '/_wms/replenishment-setup': typeof WmsReplenishmentSetupRoute
  '/_wms/reports': typeof WmsReportsRoute
  '/_wms/sales-return-grn': typeof WmsSalesReturnGrnRoute
  '/_wms/slotting': typeof WmsSlottingRoute
  '/_wms/slotting-config': typeof WmsSlottingConfigRoute
  '/_wms/unloading': typeof WmsUnloadingRoute
  '/_wms/view-dispatch': typeof WmsViewDispatchRoute
  '/_wms/view-manifest': typeof WmsViewManifestRoute
  '/_wms/wave-creation': typeof WmsWaveCreationRoute
  '/_wms/orders/$orderNo': typeof WmsOrdersOrderNoRoute
  '/_wms/pick/$picklistId': typeof WmsPickPicklistIdRoute
  '/_wms/sort/$taskId': typeof WmsSortTaskIdRoute
  '/_wms/view-pack/$packlistId': typeof WmsViewPackPacklistIdRoute
  '/_wms/view-picklist/$picklistId': typeof WmsViewPicklistPicklistIdRoute
  '/_wms/orders/': typeof WmsOrdersIndexRoute
  '/_wms/pick/': typeof WmsPickIndexRoute
  '/_wms/sort/': typeof WmsSortIndexRoute
  '/_wms/view-pack/': typeof WmsViewPackIndexRoute
  '/_wms/view-picklist/': typeof WmsViewPicklistIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/approvals'
    | '/detailed-inventory-view'
    | '/dispatch'
    | '/dock-management'
    | '/gate-entry'
    | '/grn'
    | '/item-info-update'
    | '/item-movement'
    | '/kit-mapping'
    | '/kit-order'
    | '/kitting'
    | '/manifest'
    | '/movement-task-create'
    | '/pack'
    | '/putaway'
    | '/putwall'
    | '/replenishment'
    | '/replenishment-setup'
    | '/reports'
    | '/sales-return-grn'
    | '/slotting'
    | '/slotting-config'
    | '/unloading'
    | '/view-dispatch'
    | '/view-manifest'
    | '/wave-creation'
    | '/orders/$orderNo'
    | '/pick/$picklistId'
    | '/sort/$taskId'
    | '/view-pack/$packlistId'
    | '/view-picklist/$picklistId'
    | '/orders/'
    | '/pick/'
    | '/sort/'
    | '/view-pack/'
    | '/view-picklist/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/approvals'
    | '/detailed-inventory-view'
    | '/dispatch'
    | '/dock-management'
    | '/gate-entry'
    | '/grn'
    | '/item-info-update'
    | '/item-movement'
    | '/kit-mapping'
    | '/kit-order'
    | '/kitting'
    | '/manifest'
    | '/movement-task-create'
    | '/pack'
    | '/putaway'
    | '/putwall'
    | '/replenishment'
    | '/replenishment-setup'
    | '/reports'
    | '/sales-return-grn'
    | '/slotting'
    | '/slotting-config'
    | '/unloading'
    | '/view-dispatch'
    | '/view-manifest'
    | '/wave-creation'
    | '/orders/$orderNo'
    | '/pick/$picklistId'
    | '/sort/$taskId'
    | '/view-pack/$packlistId'
    | '/view-picklist/$picklistId'
    | '/orders'
    | '/pick'
    | '/sort'
    | '/view-pack'
    | '/view-picklist'
  id:
    | '__root__'
    | '/'
    | '/_wms'
    | '/_wms/approvals'
    | '/_wms/detailed-inventory-view'
    | '/_wms/dispatch'
    | '/_wms/dock-management'
    | '/_wms/gate-entry'
    | '/_wms/grn'
    | '/_wms/item-info-update'
    | '/_wms/item-movement'
    | '/_wms/kit-mapping'
    | '/_wms/kit-order'
    | '/_wms/kitting'
    | '/_wms/manifest'
    | '/_wms/movement-task-create'
    | '/_wms/pack'
    | '/_wms/putaway'
    | '/_wms/putwall'
    | '/_wms/replenishment'
    | '/_wms/replenishment-setup'
    | '/_wms/reports'
    | '/_wms/sales-return-grn'
    | '/_wms/slotting'
    | '/_wms/slotting-config'
    | '/_wms/unloading'
    | '/_wms/view-dispatch'
    | '/_wms/view-manifest'
    | '/_wms/wave-creation'
    | '/_wms/orders/$orderNo'
    | '/_wms/pick/$picklistId'
    | '/_wms/sort/$taskId'
    | '/_wms/view-pack/$packlistId'
    | '/_wms/view-picklist/$picklistId'
    | '/_wms/orders/'
    | '/_wms/pick/'
    | '/_wms/sort/'
    | '/_wms/view-pack/'
    | '/_wms/view-picklist/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  WmsRoute: typeof WmsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_wms': {
      id: '/_wms'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof WmsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_wms/wave-creation': {
      id: '/_wms/wave-creation'
      path: '/wave-creation'
      fullPath: '/wave-creation'
      preLoaderRoute: typeof WmsWaveCreationRouteImport
      parentRoute: typeof WmsRoute
    }
    '/_wms/view-manifest': {
      id: '/_wms/view-manifest'
      path: '/view-manifest'
      fullPath: '/view-manifest'
      preLoaderRoute: typeof WmsViewManifestRouteImport
      parentRoute: typeof WmsRoute
    }
    '/_wms/view-dispatch': {
      id: '/_wms/view-dispatch'
      path: '/view-dispatch'
      fullPath: '/view-dispatch'
      preLoaderRoute: typeof WmsViewDispatchRouteImport
      parentRoute: typeof WmsRoute
    }
    '/_wms/unloading': {
      id: '/_wms/unloading'
      path: '/unloading'
      fullPath: '/unloading'
      preLoaderRoute: typeof WmsUnloadingRouteImport
      parentRoute: typeof WmsRoute
    }
    '/_wms/slotting-config': {
      id: '/_wms/slotting-config'
      path: '/slotting-config'
      fullPath: '/slotting-config'
      preLoaderRoute: typeof WmsSlottingConfigRouteImport
      parentRoute: typeof WmsRoute
    }
    '/_wms/slotting': {
      id: '/_wms/slotting'
      path: '/slotting'
      fullPath: '/slotting'
      preLoaderRoute: typeof WmsSlottingRouteImport
      parentRoute: typeof WmsRoute
    }
    '/_wms/sales-return-grn': {
      id: '/_wms/sales-return-grn'
      path: '/sales-return-grn'
      fullPath: '/sales-return-grn'
      preLoaderRoute: typeof WmsSalesReturnGrnRouteImport
      parentRoute: typeof WmsRoute
    }
    '/_wms/reports': {
      id: '/_wms/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof WmsReportsRouteImport
      parentRoute: typeof WmsRoute
    }
    '/_wms/replenishment-setup': {
      id: '/_wms/replenishment-setup'
      path: '/replenishment-setup'
      fullPath: '/replenishment-setup'
      preLoaderRoute: typeof WmsReplenishmentSetupRouteImport
      parentRoute: typeof WmsRoute
    }
    '/_wms/replenishment': {
      id: '/_wms/replenishment'
      path: '/replenishment'
      fullPath: '/replenishment'
      preLoaderRoute: typeof WmsReplenishmentRouteImport
      parentRoute: typeof WmsRoute
    }
    '/_wms/putwall': {
      id: '/_wms/putwall'
      path: '/putwall'
      fullPath: '/putwall'
      preLoaderRoute: typeof WmsPutwallRouteImport
      parentRoute: typeof WmsRoute
    }
    '/_wms/putaway': {
      id: '/_wms/putaway'
      path: '/putaway'
      fullPath: '/putaway'
      preLoaderRoute: typeof WmsPutawayRouteImport
      parentRoute: typeof WmsRoute
    }
    '/_wms/pack': {
      id: '/_wms/pack'
      path: '/pack'
      fullPath: '/pack'
      preLoaderRoute: typeof WmsPackRouteImport
      parentRoute: typeof WmsRoute
    }
    '/_wms/movement-task-create': {
      id: '/_wms/movement-task-create'
      path: '/movement-task-create'
      fullPath: '/movement-task-create'
      preLoaderRoute: typeof WmsMovementTaskCreateRouteImport
      parentRoute: typeof WmsRoute
    }
    '/_wms/manifest': {
      id: '/_wms/manifest'
      path: '/manifest'
      fullPath: '/manifest'
      preLoaderRoute: typeof WmsManifestRouteImport
      parentRoute: typeof WmsRoute
    }
    '/_wms/kitting': {
      id: '/_wms/kitting'
      path: '/kitting'
      fullPath: '/kitting'
      preLoaderRoute: typeof WmsKittingRouteImport
      parentRoute: typeof WmsRoute
    }
    '/_wms/kit-order': {
      id: '/_wms/kit-order'
      path: '/kit-order'
      fullPath: '/kit-order'
      preLoaderRoute: typeof WmsKitOrderRouteImport
      parentRoute: typeof WmsRoute
    }
    '/_wms/kit-mapping': {
      id: '/_wms/kit-mapping'
      path: '/kit-mapping'
      fullPath: '/kit-mapping'
      preLoaderRoute: typeof WmsKitMappingRouteImport
      parentRoute: typeof WmsRoute
    }
    '/_wms/item-movement': {
      id: '/_wms/item-movement'
      path: '/item-movement'
      fullPath: '/item-movement'
      preLoaderRoute: typeof WmsItemMovementRouteImport
      parentRoute: typeof WmsRoute
    }
    '/_wms/item-info-update': {
      id: '/_wms/item-info-update'
      path: '/item-info-update'
      fullPath: '/item-info-update'
      preLoaderRoute: typeof WmsItemInfoUpdateRouteImport
      parentRoute: typeof WmsRoute
    }
    '/_wms/grn': {
      id: '/_wms/grn'
      path: '/grn'
      fullPath: '/grn'
      preLoaderRoute: typeof WmsGrnRouteImport
      parentRoute: typeof WmsRoute
    }
    '/_wms/gate-entry': {
      id: '/_wms/gate-entry'
      path: '/gate-entry'
      fullPath: '/gate-entry'
      preLoaderRoute: typeof WmsGateEntryRouteImport
      parentRoute: typeof WmsRoute
    }
    '/_wms/dock-management': {
      id: '/_wms/dock-management'
      path: '/dock-management'
      fullPath: '/dock-management'
      preLoaderRoute: typeof WmsDockManagementRouteImport
      parentRoute: typeof WmsRoute
    }
    '/_wms/dispatch': {
      id: '/_wms/dispatch'
      path: '/dispatch'
      fullPath: '/dispatch'
      preLoaderRoute: typeof WmsDispatchRouteImport
      parentRoute: typeof WmsRoute
    }
    '/_wms/detailed-inventory-view': {
      id: '/_wms/detailed-inventory-view'
      path: '/detailed-inventory-view'
      fullPath: '/detailed-inventory-view'
      preLoaderRoute: typeof WmsDetailedInventoryViewRouteImport
      parentRoute: typeof WmsRoute
    }
    '/_wms/approvals': {
      id: '/_wms/approvals'
      path: '/approvals'
      fullPath: '/approvals'
      preLoaderRoute: typeof WmsApprovalsRouteImport
      parentRoute: typeof WmsRoute
    }
    '/_wms/view-picklist/': {
      id: '/_wms/view-picklist/'
      path: '/view-picklist'
      fullPath: '/view-picklist/'
      preLoaderRoute: typeof WmsViewPicklistIndexRouteImport
      parentRoute: typeof WmsRoute
    }
    '/_wms/view-pack/': {
      id: '/_wms/view-pack/'
      path: '/view-pack'
      fullPath: '/view-pack/'
      preLoaderRoute: typeof WmsViewPackIndexRouteImport
      parentRoute: typeof WmsRoute
    }
    '/_wms/sort/': {
      id: '/_wms/sort/'
      path: '/sort'
      fullPath: '/sort/'
      preLoaderRoute: typeof WmsSortIndexRouteImport
      parentRoute: typeof WmsRoute
    }
    '/_wms/pick/': {
      id: '/_wms/pick/'
      path: '/pick'
      fullPath: '/pick/'
      preLoaderRoute: typeof WmsPickIndexRouteImport
      parentRoute: typeof WmsRoute
    }
    '/_wms/orders/': {
      id: '/_wms/orders/'
      path: '/orders'
      fullPath: '/orders/'
      preLoaderRoute: typeof WmsOrdersIndexRouteImport
      parentRoute: typeof WmsRoute
    }
    '/_wms/view-picklist/$picklistId': {
      id: '/_wms/view-picklist/$picklistId'
      path: '/view-picklist/$picklistId'
      fullPath: '/view-picklist/$picklistId'
      preLoaderRoute: typeof WmsViewPicklistPicklistIdRouteImport
      parentRoute: typeof WmsRoute
    }
    '/_wms/view-pack/$packlistId': {
      id: '/_wms/view-pack/$packlistId'
      path: '/view-pack/$packlistId'
      fullPath: '/view-pack/$packlistId'
      preLoaderRoute: typeof WmsViewPackPacklistIdRouteImport
      parentRoute: typeof WmsRoute
    }
    '/_wms/sort/$taskId': {
      id: '/_wms/sort/$taskId'
      path: '/sort/$taskId'
      fullPath: '/sort/$taskId'
      preLoaderRoute: typeof WmsSortTaskIdRouteImport
      parentRoute: typeof WmsRoute
    }
    '/_wms/pick/$picklistId': {
      id: '/_wms/pick/$picklistId'
      path: '/pick/$picklistId'
      fullPath: '/pick/$picklistId'
      preLoaderRoute: typeof WmsPickPicklistIdRouteImport
      parentRoute: typeof WmsRoute
    }
    '/_wms/orders/$orderNo': {
      id: '/_wms/orders/$orderNo'
      path: '/orders/$orderNo'
      fullPath: '/orders/$orderNo'
      preLoaderRoute: typeof WmsOrdersOrderNoRouteImport
      parentRoute: typeof WmsRoute
    }
  }
}

interface WmsRouteChildren {
  WmsApprovalsRoute: typeof WmsApprovalsRoute
  WmsDetailedInventoryViewRoute: typeof WmsDetailedInventoryViewRoute
  WmsDispatchRoute: typeof WmsDispatchRoute
  WmsDockManagementRoute: typeof WmsDockManagementRoute
  WmsGateEntryRoute: typeof WmsGateEntryRoute
  WmsGrnRoute: typeof WmsGrnRoute
  WmsItemInfoUpdateRoute: typeof WmsItemInfoUpdateRoute
  WmsItemMovementRoute: typeof WmsItemMovementRoute
  WmsKitMappingRoute: typeof WmsKitMappingRoute
  WmsKitOrderRoute: typeof WmsKitOrderRoute
  WmsKittingRoute: typeof WmsKittingRoute
  WmsManifestRoute: typeof WmsManifestRoute
  WmsMovementTaskCreateRoute: typeof WmsMovementTaskCreateRoute
  WmsPackRoute: typeof WmsPackRoute
  WmsPutawayRoute: typeof WmsPutawayRoute
  WmsPutwallRoute: typeof WmsPutwallRoute
  WmsReplenishmentRoute: typeof WmsReplenishmentRoute
  WmsReplenishmentSetupRoute: typeof WmsReplenishmentSetupRoute
  WmsReportsRoute: typeof WmsReportsRoute
  WmsSalesReturnGrnRoute: typeof WmsSalesReturnGrnRoute
  WmsSlottingRoute: typeof WmsSlottingRoute
  WmsSlottingConfigRoute: typeof WmsSlottingConfigRoute
  WmsUnloadingRoute: typeof WmsUnloadingRoute
  WmsViewDispatchRoute: typeof WmsViewDispatchRoute
  WmsViewManifestRoute: typeof WmsViewManifestRoute
  WmsWaveCreationRoute: typeof WmsWaveCreationRoute
  WmsOrdersOrderNoRoute: typeof WmsOrdersOrderNoRoute
  WmsPickPicklistIdRoute: typeof WmsPickPicklistIdRoute
  WmsSortTaskIdRoute: typeof WmsSortTaskIdRoute
  WmsViewPackPacklistIdRoute: typeof WmsViewPackPacklistIdRoute
  WmsViewPicklistPicklistIdRoute: typeof WmsViewPicklistPicklistIdRoute
  WmsOrdersIndexRoute: typeof WmsOrdersIndexRoute
  WmsPickIndexRoute: typeof WmsPickIndexRoute
  WmsSortIndexRoute: typeof WmsSortIndexRoute
  WmsViewPackIndexRoute: typeof WmsViewPackIndexRoute
  WmsViewPicklistIndexRoute: typeof WmsViewPicklistIndexRoute
}

const WmsRouteChildren: WmsRouteChildren = {
  WmsApprovalsRoute: WmsApprovalsRoute,
  WmsDetailedInventoryViewRoute: WmsDetailedInventoryViewRoute,
  WmsDispatchRoute: WmsDispatchRoute,
  WmsDockManagementRoute: WmsDockManagementRoute,
  WmsGateEntryRoute: WmsGateEntryRoute,
  WmsGrnRoute: WmsGrnRoute,
  WmsItemInfoUpdateRoute: WmsItemInfoUpdateRoute,
  WmsItemMovementRoute: WmsItemMovementRoute,
  WmsKitMappingRoute: WmsKitMappingRoute,
  WmsKitOrderRoute: WmsKitOrderRoute,
  WmsKittingRoute: WmsKittingRoute,
  WmsManifestRoute: WmsManifestRoute,
  WmsMovementTaskCreateRoute: WmsMovementTaskCreateRoute,
  WmsPackRoute: WmsPackRoute,
  WmsPutawayRoute: WmsPutawayRoute,
  WmsPutwallRoute: WmsPutwallRoute,
  WmsReplenishmentRoute: WmsReplenishmentRoute,
  WmsReplenishmentSetupRoute: WmsReplenishmentSetupRoute,
  WmsReportsRoute: WmsReportsRoute,
  WmsSalesReturnGrnRoute: WmsSalesReturnGrnRoute,
  WmsSlottingRoute: WmsSlottingRoute,
  WmsSlottingConfigRoute: WmsSlottingConfigRoute,
  WmsUnloadingRoute: WmsUnloadingRoute,
  WmsViewDispatchRoute: WmsViewDispatchRoute,
  WmsViewManifestRoute: WmsViewManifestRoute,
  WmsWaveCreationRoute: WmsWaveCreationRoute,
  WmsOrdersOrderNoRoute: WmsOrdersOrderNoRoute,
  WmsPickPicklistIdRoute: WmsPickPicklistIdRoute,
  WmsSortTaskIdRoute: WmsSortTaskIdRoute,
  WmsViewPackPacklistIdRoute: WmsViewPackPacklistIdRoute,
  WmsViewPicklistPicklistIdRoute: WmsViewPicklistPicklistIdRoute,
  WmsOrdersIndexRoute: WmsOrdersIndexRoute,
  WmsPickIndexRoute: WmsPickIndexRoute,
  WmsSortIndexRoute: WmsSortIndexRoute,
  WmsViewPackIndexRoute: WmsViewPackIndexRoute,
  WmsViewPicklistIndexRoute: WmsViewPicklistIndexRoute,
}

const WmsRouteWithChildren = WmsRoute._addFileChildren(WmsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  WmsRoute: WmsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
